### ISSUE TITLE
Allow Fluent Configuration of RetryTemplate

### ISSUE THREAD

**Issue by romeara** [spring-projects/spring-retry#116]
A lot of spring projects allow a fluent configuration of their objects (builders/configurers) to make setup a bit easier - it would be great to add an ease-of-use option such as this. RetryInterceptorBuilder is already present, and it would nice to have something similar for RetryTemplate.

(Note: I'll try to get some time to put a PR together to propose, assuming the concept in general sounds desirable to the project, as I know the above is a little vague and it would be easier to discuss with a concrete example - I'll post snippets in here for discussion as I fiddle with it)

**Comment by ashamukov** [comment]
Hello! Came up with the same idea, and found the issue:) @wpanas , if your plans change, tell, I can help

**Comment by dsyer** [comment]
Closed in #153

**Comment by ashamukov** [comment]
Thanks a lot!
