### ISSUE TITLE
ExponentialRandomBackOffPolicy counts incorrect sleep intervals

### ISSUE THREAD

**Issue by ondrejvelisek** [spring-projects/spring-retry#126]
Hey there, 

Spec says:
Example: initialInterval = 50 multiplier = 2.0 maxInterval = 3000 numRetries = 5 ExponentialBackOffPolicy yields: [50, 100, 200, 400, 800] ExponentialRandomBackOffPolicy may yield [50, 100, 100, 100, 600] or [50, 100, 150, 400, 800]

However if I look to implementation
```
public synchronized long getSleepAndIncrement() {
			long next = super.getSleepAndIncrement();
			next = (long) (next * (1 + r.nextFloat() * (getMultiplier() - 1)));
			return next;
		}
```

It means result will be never less than super method result. So either spec is wrong or implementation. Also tested several times.  Am I missing something?

Thanks and Cheers

**Comment by Rajh** [comment]
Hi,
I'd like to add that maxInterval seems to be ignored.
If we reach maxInterval in super.getSleepAndIncrement() from ExponentialBackOffPolicy
The ExponentialRandomBackOffPolicy will always be > to the max.

**Comment by shahamit** [comment]
True. The maxInterval is ignored. It is checked in the super class but not in the sub class. Can this bug be prioritized? Looks like a simple fix.

**Comment by artembilan** [comment]
Sounds like you are fully on board with the issue!

We will appreciate a contribution via Pull Request.
That indeed will prioritize an issue and more chances to have fix merged into the `master`.

Thanks for heads up!

**Comment by abracadv8** [comment]
The fix looks easy enough.

It looks like the documentation about the random values changed a bit, but I added an extra line describing the min-max ranges for each interval.

Let me know if you have any suggestions for changes.

I have previously signed the Pivotal CLA on behalf of Comcast Corporation for other Spring projects.

**Comment by abracadv8** [comment]
@artembilan - Can you take a review of this pull request and provide any feedback?
