### ISSUE TITLE
Retry capacity

### ISSUE THREAD

**Issue by fabienmifsud** [spring-projects/spring-retry#132]
Hi,
I'm about to use spring-retry on a kafka consumer method. This consumer call an external WS based on kafka message. If this external WS turns down, we want to retry for a few hours with the hope that the WS will turn up again. What happens if there are too many retry queued ? If there a way to store them somewhere ? In a cluster context, if my app turns down, can i share retries to other members of my cluster ?
Am I choosing a bad technology for my need ?

Thx!

**Comment by garyrussell** [comment]
The thread is suspended during retry backoff there is no "queue"; the number of requests is limited by the upstream threading.

**Comment by garyrussell** [comment]
The thread is suspended during retry backoff there is no "queue"; the number of requests is limited by the upstream threading.

If you suspend too long though, Kafka will think the consumer is dead and rebalance the partitions; you would need to increase `max.poll.interval.ms`.

**Comment by fabienmifsud** [comment]
Ok, so If I have 3 consumers, and a pending retry on each, no more messages will be consumed.
That can be fine for our use case. I'll check the poll interval to be sure not loosing my consumer.

Thank you !
