### ISSUE TITLE
spring-retry 1.2.4 with Spring 4.3.22 complains about missing Aspect dependencies

### ISSUE THREAD

**Issue by Ghilteras** [spring-projects/spring-retry#147]
Hi, I'm trying to add a `@Retryable` annotation to one of my methods and since I cannot use a `@Configuration` class I am doing it with xml in my spring `<beans>` like this:

```
    <context:annotation-config />
    <aop:aspectj-autoproxy />
    <bean id="retryAdvice"
          class="org.springframework.retry.interceptor.RetryOperationsInterceptor"/>
```

My application complains about `Pointcut` not being available

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.aop.config.internalAutoProxyCreator': Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: org/aspectj/lang/annotation/Pointcut
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
Caused by: java.lang.NoClassDefFoundError: org/aspectj/lang/annotation/Pointcut
	at org.springframework.aop.aspectj.annotation.AbstractAspectJAdvisorFactory.<clinit>(AbstractAspectJAdvisorFactory.java:62)
Caused by: java.lang.ClassNotFoundException: org.aspectj.lang.annotation.Pointcut
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
```

but it's in my classpath according to maven as part of aspectjweaver 1.8.9

```
# mvn dependency:tree
[INFO] +- org.springframework.retry:spring-retry:jar:1.2.4.RELEASE:compile
[INFO] +- org.springframework:spring-aop:jar:4.3.22.RELEASE:compile
[INFO] |  \- org.springframework:spring-beans:jar:4.3.22.RELEASE:compile
[INFO] +- org.springframework:spring-core:jar:4.3.22.RELEASE:compile
[INFO] +- org.springframework:spring-aspects:jar:4.3.22.RELEASE:compile
[INFO] |  \- org.aspectj:aspectjweaver:jar:1.8.9:compile
```

As you can see I'm using Spring 4.3.22, but It looks like that adding `spring-aspects` as dependency is not enough to make `spring-retry` work? Am I missing something?

**Comment by dsyer** [comment]
I didn't really understand why you have to use XML (given than you are using the XML to switch on annotation processing, so you must be using annotations as well). Anyway `spring-aspects` has nothing to do with retry so you won't need that unless you use the features in there, but it isn't actually hurting I guess. If you want to use `<aop:aspectj-autoproxy />` you need to use AspectJ (not Spring AOP). Is that really what you wanted? If so go and read the documentation on Spring with AspectJ (and there are some samples [here](https://github.com/dsyer/spring-boot-aspectj)). If not, just put `spring-aop` and `aspectjweaver` on your classpath and `@EnableAspectJAutoProxy` (or whatever that is in XML).

**Comment by dsyer** [comment]
I didn't really understand why you have to use XML (given than you are using the XML to switch on annotation processing, so you must be using annotations as well). Anyway `spring-aspects` has nothing to do with retry so you won't need that unless you use the features in there, but it isn't actually hurting I guess. If not, just put `spring-aop` and `aspectjweaver` on your classpath and `@EnableAspectJAutoProxy` (or the XML version) and it should work.  If it isn't I suspect that your XML might not be in the application context at all.

**Comment by dsyer** [comment]
Don’t you need to `@EnableRetry` as well? (Or add a bean that does the same thing.)

**Comment by Ghilteras** [comment]
I understand that `EnableRetry` is needed and it has to go on the @Configuration class, but like I said all my Spring configuration is done via xml (I'm writing a plugin for Shibboleth https://wiki.shibboleth.net/confluence/display/IDP30/SpringConfiguration which is all Spring xml) so I'd rather stick to that and in any case even if I create an empty class with @Configuration and @EnableRetry it doesn't work (probably because nothing in the Shibboleth Spring Web flow references that class and it does not get picked up)

Anyway, about the dependencies: `spring-aop` was already there, see my `mvn dependency:tree` above? I tried adding `aspectweaver` 1.9.2 to my `pom.xml` and it does not change anything, I still get the same error

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.aop.config.internalAutoProxyCreator': Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: org/aspectj/lang/annotation/Pointcut
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
Caused by: java.lang.NoClassDefFoundError: org/aspectj/lang/annotation/Pointcut
	at org.springframework.aop.aspectj.annotation.AbstractAspectJAdvisorFactory.<clinit>(AbstractAspectJAdvisorFactory.java:62)
Caused by: java.lang.ClassNotFoundException: org.aspectj.lang.annotation.Pointcut
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
```

Any other hint?

**Comment by dsyer** [comment]
AFAIK that class is in the aspectj weaver jar (you could check). If so then you have a classloader/classpath issue more than a spring issue.

**Comment by Ghilteras** [comment]
I can just manually use `@Pointcut` with `import org.aspectj.lang.annotation.Pointcut`, so I'm pretty cure my classpath is fine, is this all I need in xml to achieve the same as `@EnableRetry` ?

```
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:aop="http://www.springframework.org/schema/aop"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
                           http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context.xsd
                           http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop-3.0.xsd"
       default-init-method="initialize" default-destroy-method="destroy">
    <context:annotation-config />
    <aop:aspectj-autoproxy />
```

**Comment by dsyer** [comment]
If you look at `@EnableRetry` you will see that it does more than that. But even if you add the missing features it won’t solve your classpath issue.

**Comment by Ghilteras** [comment]
I still cannot find any classpath issue. Do I need to do the aspect weaving at compile time instead of runtime?

**Comment by Ghilteras** [comment]
I think the problem was that aspectj jars need to be copied as hard dependencies, I used `maven-dependency-plugin` with `copy-dependencies` on the aspect dependencies and now the class not found errors are gone. `@Retryable` is still not retrying thgouhg, but I'll file a different issue for that, we can close this one.

**Comment by HeliPatel91** [comment]
@Ghilteras I am also facing the same issue with annotation configuration when adding the annotation @EnableRetry in my spring boot application class.  
Please let me know what you did to solve the issue.

**Comment by samirm** [comment]
@Ghilteras were you ever able to resolve your retry issues?

facing the same problem where Retry no longer triggers anymore for some reason

**Comment by artembilan** [comment]
This is an old issue. Would be great if you upgrade to the latest one, at least: https://github.com/spring-projects/spring-retry/releases/tag/v1.3.4
