### ISSUE TITLE
Only one method in class can be marked as @Retryable

### ISSUE THREAD

**Issue by dzahusta** [spring-projects/spring-retry#15]
Why only one method in class can be marked as `@Retryable`. It doesn't look reasonable enough. You can have several methods which need to be retryable - for example DAO service.

**Comment by puneet-kumar-onestopbuddies** [comment]
Can you introduce methodName in @recover annotation to point to exact method. Right now, its of no use if you want to get recovery of multiple methods

**Comment by dsyer** [comment]
Please don't start new discussions on old, closed issues. If you have a new requirement, open a new issue.  Send a pull request, if you want.
