### ISSUE TITLE
First retry not attempted with maxAttempts setting of 1 in SimpleRetryPolicy

### ISSUE THREAD

**Issue by edavedian** [spring-projects/spring-retry#152]
Hello,

I have the following configuration in my application for a retry to occur on an occurrence of UnknownHostException from any calls to RestTemplate.  Now when I set the maxAttempts in SimpleRetryPolicy to 1, the listener's 'onError' gets called but the actual retry doesn't occur.  I could only get the retry to execute if I set the maxAttempts to 2.
Also the listener's 'onError' is getting called for all exception thrown from RestTemplate even though I have only specified 'UnknownHostException' for retryableExceptions and that is very confusing because we think that a retry is occurring for all exceptions.  
Could I ask you to please clarify if this behavior is correct or if I am missing something in the configuration.

```
    <aop:config>
        <aop:pointcut id="retryOnException" 
        	expression="execution(* org.springframework.web.client.RestTemplate.*(..))" />
        <aop:advisor pointcut-ref="retryOnException" advice-ref="taskRetryAdvice" order="-1" />
    </aop:config>
 
    <bean id="taskRetryAdvice" class="org.springframework.retry.interceptor.RetryOperationsInterceptor">
        <property name="RetryOperations" ref="taskRetryTemplate" />
    </bean>
 
  <bean id="retryListener" class="com.mycompany.cnsb.common.CnsbRetryListener" />
	
  <bean id="taskRetryTemplate" class="org.springframework.retry.support.RetryTemplate">
        <property name="retryPolicy" ref="taskRetryPolicy" />
        <property name="listeners">
        	<list>
			    <ref bean="retryListener" />
			</list>
        </property>
    </bean>
 
    <bean id="taskRetryPolicy" class="org.springframework.retry.policy.SimpleRetryPolicy">
        <constructor-arg index="0" value="2" />
        <constructor-arg index="1">
            <map>
                <entry key="java.net.UnknownHostException" value="true" />
            </map>
        </constructor-arg>
        <constructor-arg index="2" value="true" />
    </bean>
```

**Comment by dsyer** [comment]
I think that's the intended behaviour. The first try is the last.

**Comment by edavedian** [comment]
@dsyer I would think the first attempt shouldn't count as a retry.

**Comment by dsyer** [comment]
That’s fair. But it’s not the way it was implemented.
