### ISSUE TITLE
Where can I find current documentation?

### ISSUE THREAD

**Issue by coreyjv** [spring-projects/spring-retry#17]
I see in Maven Central that the latest release of Spring Retry is `1.1.2`, but when I go to the following link for documentation http://static.springsource.org/spring-retry/docs/api/current/ it's for version `1.0.3`. Is there another location where the most recent documentation is posted?

Thanks!

**Comment by vab2048** [comment]
The latest docs here: https://docs.spring.io/spring-retry/docs/ are for 1.2.2.RELEASE whereas the latest release is 1.2.4. Is it possible for you to release the latest version's docs as well, please?

This would have helped avoid the confusion I was having when looking at the RetryTemplate docs (https://docs.spring.io/spring-retry/docs/api/current/org/springframework/retry/support/RetryTemplate.html) and not seeing the builder method that is now available there.

The all classes page for the docs (https://docs.spring.io/spring-retry/docs/api/current/allclasses-noframe.html) also currently does not have RetryTemplateBuilder there so I could not see the options/examples available to use with the builder.

I have fallen back to looking directly at the source (which is of course useful) but it would still be useful to have the latest docs published. 

Thanks

**Comment by dsyer** [comment]
How about here: https://www.javadoc.io/doc/org.springframework.retry/spring-retry/1.2.4.RELEASE

**Comment by vab2048** [comment]
Thank you. I was unaware of javadoc.io. It seems very useful.
