### ISSUE TITLE
Is there a way to use @Retryable during spring context initialization with XML configuration?

### ISSUE THREAD

**Issue by edavedian** [spring-projects/spring-retry#177]
@garyrussell I used the configuration suggested in https://github.com/spring-projects/spring-retry/issues/27 but RetryConfiguration is getting initialized after the beans that are annotated with `@Retryable` and need retry functionality during spring context initialization.  Is there a way to make RetryConfiguration be initialized very early in spring context initialization using XML?

**Comment by edavedian** [comment]
To clarify the use case, the database credentials used by the application are managed by another team and these credentials are completely abstracted away from the application and securely tucked in a vault.  In order to create a data source during sprint context initialization, we need to retrieve the database credentials from the vault.  The entire initialization is dependent upon the successful creation of the data source and if during the retrieval there are intermittent SocketTimeoutException occurrences then we would like to have retries in place for further attempts.

**Comment by garyrussell** [comment]
@edavedian You should really not connect to a database during the bean creation phase; instead, implement `SmartLifecyle`, put your bean in an appropriate `Phase` and connect in the `start()` method.

**Comment by edavedian** [comment]
@garyrussell Thank you very much.  What options do we have if we are using initializing `org.apache.commons.dbcp2.BasicDataSource` directly?

**Comment by garyrussell** [comment]
Directly where? Show your code/config.

**Comment by edavedian** [comment]
Directly in the XML configuration as follows:

```
<bean name="dataSource" class="org.apache.tomcat.jdbc.pool.DataSource">
	<property name="driverClassName" value="oracle.jdbc.OracleDriver" />
        <property name="url" value="#{dbConfigProperties.getJdbcUrl()}" />
        <property name="username" value="#{dbConfigProperties.getJdbcUsername()}" /> 
        <property name="password" value="#{dbConfigProperties.getJdbcPassword()}" />
</bean>
```

**Comment by garyrussell** [comment]
Just adding a `DataSource` bean won't create a connection, you must be trying to talk to the database before the application context is fully initialized.

**Comment by edavedian** [comment]
@garyrussell Thank you very much.  Yes, we are making connection to database in initialization phase.  We will make changes to make connections in `start` phase.
