### ISSUE TITLE
Spring Retry causes RetryListener beans to be initialised early, making them and their dependencies ineligible for post-processing

### ISSUE THREAD

**Issue by chengchen** [spring-projects/spring-retry#178]
Hello,

I have submitted an issue in Spring Boot before [#16977](https://github.com/spring-projects/spring-boot/issues/16977), since I thought the fix could be performed over there. But @wilkinsona suggested that the fix should probably be done here (I am not 100% sure though). Could you please take a look at it?

Many thanks!

Chengchen

**Comment by artembilan** [comment]
This was fixed as a side-effect of the change: https://github.com/spring-projects/spring-retry/pull/286
