### ISSUE TITLE
need extended support on exception handling

### ISSUE THREAD

**Issue by 5aab** [spring-projects/spring-retry#179]
I have a requirement which I want to implement with the *spring-retry* **RetryTemplate**. The requirement is as follow
1)  if exception ex1 is thrown, an instance of Class A1 should be called out of the box
2) if exception ex2 is thrown,  an instance of Class A2 should be called out of the box

I know there is a **RetryListenerSupport**, but that is set at the template level and not at the policy level. can you please enhance *spring-retry* to handle above case. **Thanks**

**Comment by artembilan** [comment]
This sounds like a `@Recover` feature: https://github.com/spring-projects/spring-retry#-java-configuration-for-retry-proxies.
You can have several `@Recover` methods for different exceptions and there you already can call those instances you mention in the request.

Closing as `Works as Designed`
