### ISSUE TITLE
RetryListener can't easily determine if the retry will be retried or not

### ISSUE THREAD

**Issue by steveash** [spring-projects/spring-retry#18]
I want to use the retryListener to be able to log WARNs when I do the retry and ERRORs when I am going to eventually rethrow it.  I'm using spring-retry to manage the "exception policy" for my web service so it sits at the uppermost layer of my software.  Thus I want to handle exception logging at this layer.  Unfortunately I cannot easily determine inside the onError method whether or not the given throwable will be retried or not.  Sure I can get the current attempt count from the context, and if my listener has a reference to the retry policy I _could_ call canRetry -- but that doesn't help because at the point when RetryTemplate calls onError -- it hasn't yet caled registerThrowable.

This seems like a pretty reasonable feature that should be supported.  A simple, backwards compatible way would just be to registerThrowable before calling onError.  I think that makes the context.getLastThrown make more sense anyways from the perspective of the listener.  Or there's of course more appropriate but less backwards compatible ways.

If you can't see a problem with changing the order to call registerThrowable before onError - I can submit a PR for that today.

**Comment by dsyer** [comment]
The listener contract is a bit bizarre for historical reasons (sorry). We should look at it for 1.2 or 2.0. In the meantime there is a `StatisticsListener` that does a lot of heavy lifting analysing the actual state of the policy and relaying it into stats. Maybe you can use that or copy bits of it?

**Comment by artembilan** [comment]
[This commit](https://github.com/spring-projects/spring-retry/commit/1cb4f19c) has made a change requested in this issue as a side effect of other premise.
So, since the current code is like this:
```
					try {
						registerThrowable(retryPolicy, state, context, e);
					}
					catch (Exception ex) {
						throw new TerminatedRetryException("Could not register throwable", ex);
					}
					finally {
						doOnErrorInterceptors(retryCallback, context, e);
					}
```
I treat this issue as `Fixed`.
