### ISSUE TITLE
@Retryable methods are not intercepted when called from same bean

### ISSUE THREAD

**Issue by joshfoeh** [spring-projects/spring-retry#180]
If you call a @Retryable method directly on a bean, it works as expected. The call is intercepted by a CglibAopProxy, which then wraps the intended call in a try catch and retries as necessary.

However, if you call another non @Retryable method on that same bean, which then internally calls the @Retryable method, that call is not intercepted. Any exception thrown by the @Retryable method is thrown as it normally would be and not caught by a proxy, which causes the retry functionality to not happen.

Of course this is possible to get around by only ever calling @Retryable methods from outside of the bean, but there are cases where only delegating to the @Retryable method some of the time makes sense and it would be beneficial to encapsulate all logic inside one class. 

For example, I encountered this while making a client factory that provides a client already connected to a messaging broker. If the client is already connected then return it, but if it is not then attempt to connect it with retries.

If this is intended/known functionality then I believe it should be mentioned more clearly in the docs as I saw no mention of this behavior.

Sample project exhibiting this behavior can be found here: https://github.com/joshfoeh/spring-retry-test The TestProxy#testProxiedRetrySuccess test performs the situation I describe above and throws an exception instead of retrying.

**Comment by artembilan** [comment]
Have you tried like this `@EnableRetry(proxyTargetClass = true)` ?

I mean it feels like your class should be fully proxied, so any calls internally lead to the top proxy interception.

**Comment by joshfoeh** [comment]
@artembilan Thanks for the quick response. I just tried that (on both the test and normal config) and it didn't seem to change anything, still having the same issue.

**Comment by artembilan** [comment]
Well, after some investigation I realized that I misled you a little bit.
So, the proxy option to intercept its own methods is called `exposeProxy`:
```
/**
 * Set whether the proxy should be exposed by the AOP framework as a
 * ThreadLocal for retrieval via the AopContext class. This is useful
 * if an advised object needs to call another advised method on itself.
 * (If it uses {@code this}, the invocation will not be advised).
 * <p>Default is "false", in order to avoid unnecessary extra interception.
 * This means that no guarantees are provided that AopContext access will
 * work consistently within any method of the advised object.
 */
public void setExposeProxy(boolean exposeProxy) {
```

But it still doesn't work somehow ever if I use it like this:
```
@EnableAspectJAutoProxy(exposeProxy = true, proxyTargetClass = true)
@EnableRetry
```

I see everything is configured on the target proxy at runtime, but it still doesn't go through the interceptors...

So, the best way is do not call methods with retry from the same object.

But I'd really would like to understand what may be missing in our observations, @dsyer .
Thanks

**Comment by joshfoeh** [comment]
Thanks for the update, after some more searching around of my own I came across [this SO answer](https://stackoverflow.com/questions/13564627/spring-aop-not-working-for-method-call-inside-another-method/13564700#13564700) that seems to be describing the same issue. Looks like it's just the behavior of AOP and Spring. In the meantime I have just restructured my code a little bit to not call the Retryable method from within the same object.

**Comment by liavyona** [comment]
@artembilan Do you have a solution for this issue now?

**Comment by sregger** [comment]
I understood this issue better after reading a comment in a StackOverflow [question](https://stackoverflow.com/questions/38212471/springboot-retryable-not-retrying). Namely

> thats a generic spring thing, you can use @Autowired self reference? 

Basically the `@Retryable` proxy is only being setup when the bean is initialised. That means the reference returned by

    @AutoWired MyObject myObject;

Is not the actual object but instead a proxy with support for @Retryable. The problem in the code here is that you're not using that proxy when calling the method locally

    this.myRetyableMethod()

Is using the bare object rather than the proxy. This is more understandable but still a catch ya bad design.
