### ISSUE TITLE
maybe some word should be change in README.md?

### ISSUE THREAD

**Issue by ZhangChaoWN** [spring-projects/spring-retry#190]
in README.md it is said that:

> or a partial list of them as long as none are omitted

should it be changed to:

or a partial list of them as long as **some** are omitted?

I looked up some dictionaries before submit this issue, I'm not good as English, please correct me if I'm wrong.

**Comment by dsyer** [comment]
I think the original wording is correct, if maybe unclear. I attempted to clarify it.
