### ISSUE TITLE
Enabling commit c12bf15 on branch 1.2.X

### ISSUE THREAD

**Issue by Nocturne183** [spring-projects/spring-retry#195]
Currently the latest release version of spring retry is 1.2.5.RELEASE which does not contain commit [c12bf15 ](https://github.com/spring-projects/spring-retry/commit/c12bf151341d085685fe79bb99f196ee84a8925f).

Is there any chance that this will be released on branch 1.2.X soon?

**Comment by dsyer** [comment]
That change is not on the 1.2.x branch. I'm not sure it ought to be, but if anyone wants to port it and make the argument that it isn't a breaking change, it's possible we could see it happen.

**Comment by artembilan** [comment]
@dsyer , it's definitely not a breaking change. 
We have introduced a new annotation attribute with default behavior as it was before without such an attribute.
So, if your old app upgrades to the latest `1.2.x`, it doesn't mean that behavior will change for you. Until, of course, you bump to the situation described in the issue with multiple retryable methods. There you will need that new option.

Thanks

**Comment by artembilan** [comment]
The version `1.2.x` is EOL already. 
Minimum you have to upgrade to the latest `1.3.x` or better to `2.0.x` which is based on the latest Spring Framework already and has much more fixes and features.
