### ISSUE TITLE
Slight confusion about the state of this. 1.3?

### ISSUE THREAD

**Issue by MonoAnji** [spring-projects/spring-retry#200]
So there's a 3 months old README in this project promoting the imperative RetryTemplate, but such a version doesn't seem to exist anywhere. Was this planned and dropped? The spring website doesn't really seem to know about this project either so it feels like it may either be outdated or not really supported. Either way I'd have really liked the 1.3. version... if it existed.

**Comment by MonoAnji** [comment]
Well, I could go for https://repo.spring.io/libs-snapshot-local/org/springframework/retry/spring-retry/1.3.0.BUILD-SNAPSHOT/ ... I guess the actual release is upcoming, just a bit confused about the Readme on master implying that such a version exists since a couple of months. Sorry. :)

**Comment by dsyer** [comment]
Sorry for the confusion. Master is 1.3 (which is not yet released as you noticed, but there is nothing blocking it as far as I know), so that's what the README describes. Hopefully it's clearer once you know that.

**Comment by dsyer** [comment]
1.3.0 is in Maven Central now.
