### ISSUE TITLE
stateful @Retryable doesn't retry 

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-retry#21]
```java
@Component
public class TransferService {

	private AtomicInteger count = new AtomicInteger(0);

	@Retryable(include = ConcurrencyFailureException.class, stateful = true)
	@Transactional
	public void transfer(String fromAccountNo, String toAccountNo,BigDecimal amount) {
		// do transaction
		int i = count.addAndGet(1);
		if (i % 3 != 0) // rollback
			throw new OptimisticLockingFailureException("data already changed");
	}

}
```
it only attempt once and throw exception, I expect attempt three times and doesn't throw exception.

**Comment by deragon** [comment]
I do not see you using @EnableRetry.  Without it, the annotation does not do anything.  Try with:

````java
@Component
@EnableRetry
public class TransferService {
  ...
}
```

Also just try with @Retryable without arguments if it still does not work.  Ensure that your TransferService class is found by Spring with @ComponentScan or another mechanism.

**Comment by jasonbwtan** [comment]
I get the same result as quaff (with using @EnableRetry).
@retryable doesn't retry with stateful = true. However when stateful = false is set, the expected behaviour occurs.

**Comment by bwzhang2011** [comment]
@jasonbwtan, any update with such issue ? stateful retry is supported or not ?

**Comment by jasonbwtan** [comment]
@bwzhang2011 its working. i was mistaken.

**Comment by quaff** [comment]
@jasonbwtan , what did you mistaken?

**Comment by kbucksch** [comment]
@bwzhang2011 would be nice to get your solution.

**Comment by SrinivasareddyGatla** [comment]
I have the same issue, any solution found ?

**Comment by dsyer** [comment]
There is no issue. This is the expected behaviour (read the docs on stateful retry).
