### ISSUE TITLE
Javadoc not accurate for org.springframework.retry.backoff.ExponentialBackOffPolicy

### ISSUE THREAD

**Issue by mkdaly** [spring-projects/spring-retry#210]
The [javadoc for ExponentialBackOffPolicy](https://github.com/spring-projects/spring-retry/blob/cfabf26c419d0cb9afefb13708b0a1772df38f4b/src/main/java/org/springframework/retry/backoff/ExponentialBackOffPolicy.java#L32) states"The setInitialInterval(long) property controls the initial value passed to Math.exp(double) and the setMultiplier(double) property controls by how much this value is increased for each subsequent attempt." However, Math.exp(double) is not called in the class.

**Comment by zyexal** [comment]
@garyrussell please re-open

[Here](https://github.com/spring-projects/spring-retry/blob/f25d6e8ff476f331ef724228f8c1575dc429df4a/src/main/java/org/springframework/retry/backoff/ExponentialBackOffPolicy.java#L27) and [here](https://github.com/spring-projects/spring-retry/blob/f25d6e8ff476f331ef724228f8c1575dc429df4a/src/main/java/org/springframework/retry/backoff/ExponentialBackOffPolicy.java#L170) the java-doc is still wrong, resp. is talking about `Math.exp(double)`. Thanks.
