### ISSUE TITLE
Ability to exit before all retry attempts based upon some condition

### ISSUE THREAD

**Issue by brijeshprasad89** [spring-projects/spring-retry#218]
I have a Retry implemented which would run every 5 seconds and would try for 5 times. However, I would like to exit from Retry when some condition is met.
So let's say, I am on retryCount=3, and the condition is met, it would exit from the Retry function and won't execute for 4th and 5th iterations. Is there such a way to achieve this using Retry?

More details on the stackoverflow question : https://stackoverflow.com/questions/63882173/exit-before-all-attempts-in-spring-retryable

**Comment by garyrussell** [comment]
Don't ask the same questions in multiple places; it is a waste of your time and ours; I answered there.

In any case, GitHub issues are not for asking questions; they are for reporting bugs or asking for new features.
