### ISSUE TITLE
RecoverAnnotationRecoveryHandler does not get recover method name from interface

### ISSUE THREAD

**Issue by txcodemonkey** [spring-projects/spring-retry#219]
Would it be better to have the init method use AnnotationUtils to find the annotation instead of calling it from the method?  If the annotations are applied on the interface instead of the implementation the recover method name is not found.

**Comment by dsyer** [comment]
Can you be more specific (line numbers, or code snippets)? I see `AnnotationUtils` used in `RecoverAnnotationRecoveryHandler` already, so it's not quite clear what you mean.

**Comment by txcodemonkey** [comment]
It was line 165, but it was fixed with the pull request that was merged this morning.  I'm closing this issue.
