### ISSUE TITLE
support custom RetryConfiguration.getOrder() via @EnableRetry like @EnableAsync

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-retry#22]
``` java
@EnableRetry(order = -1)
@Configuration
public class RetryConfiguration {

}

```

configure @Retryable before @Transactional, so we can handle transaction with stateless @Retryable,  is stateful necessary anymore?

**Comment by headstar** [comment]
+1

**Comment by headstar** [comment]
Is it correct to say that the transactional advisor and retryable advisor are unordered in the snippet below? (using @EnableRetry).
```
@Transactional
@Retryable
@Service
public class FooService {
}
```

**Comment by quaff** [comment]
Yes, you can do this
```xml
<tx:annotation-driven order="0"/>
```
```java
@Configuration
public class RetryConfiguration extends
		org.springframework.retry.annotation.RetryConfiguration {

	@Override
	public int getOrder() {
		return -1;
	}

}
```

**Comment by headstar** [comment]
Ok, thanks.

**Comment by aartigao** [comment]
Hey, I'm looking for this feature. Are there any plans on implement it?

**Comment by quaff** [comment]
ping

**Comment by DieterVDW** [comment]
Pong!

Is this project still being maintained?

**Comment by ejust** [comment]
+ 1

**Comment by yoorick** [comment]
+1 for this feature.

We have multiple advisors in our project, and a `MethodInvocation` usually consists of a chain of two or more `MethodInterceptor`s, and a particular order of them is important.

Now we have to use an approach similar to what @quaff showed above.

**Comment by wtritch** [comment]
In case others are still having this issue, we ran into a problem using a `@Backoff` annotation in a `@Retryable @Transactional`-annotated method.  The `@Backoff` annotation includes an `@Import(RetryConfiguration.class)` which leads to double-registering retry AOP Advice (one for the class extending RetryConfiguration, and one for the imported RetryConfiguration.)

After some mucking around with Spring's configuration loading we decided on manually setting the RetryConfiguration order in a `@PostConstruct` which needs to be executed PRIOR to instantiating any advised beans.  (Once a bean is advised the advice order is locked.)
```
@Configuration
@Order(Ordered.HIGHEST_PRECEDENCE)
@EnableRetry
public class OrderRetryConfiguration {

    @Autowired
    public RetryConfiguration retryConfiguration;

    @PostConstruct
    public void postConstruct() {
        this.retryConfiguration.setOrder(Ordered.LOWEST_PRECEDENCE - 1);
    }
}
```

**Comment by philippthiele** [comment]
> In case others are still having this issue, we ran into a problem using a `@Backoff` annotation in a `@Retryable @Transactional`-annotated method. The `@Backoff` annotation includes an `@Import(RetryConfiguration.class)` which leads to double-registering retry AOP Advice (one for the class extending RetryConfiguration, and one for the imported RetryConfiguration.)
> 
> After some mucking around with Spring's configuration loading we decided on manually setting the RetryConfiguration order in a `@PostConstruct` which needs to be executed PRIOR to instantiating any advised beans. (Once a bean is advised the advice order is locked.)
> 
> ```
> @Configuration
> @Order(Ordered.HIGHEST_PRECEDENCE)
> @EnableRetry
> public class OrderRetryConfiguration {
> 
>     @Autowired
>     public RetryConfiguration retryConfiguration;
> 
>     @PostConstruct
>     public void postConstruct() {
>         this.retryConfiguration.setOrder(Ordered.LOWEST_PRECEDENCE - 1);
>     }
> }
> ```

You seem to be correct, using backoff breaks @Retryable in combination with @Transactional. The Configuration you linked above does not fix that for me though.

**Comment by flozano** [comment]
This issue looks important, any other workaround? 

right now I'm reverting to having a service decorator with manual handling of retries with retryTemplate, which is far from ideal.

**Comment by quaff** [comment]
@garyrussell Could you take a look at this?

**Comment by frankjkelly** [comment]
Interesting - for those of use waiting to go to Spring Retry 2.0.0 what is the advice to get correct operation of code like the following

```
    @Retryable(backoff = @Backoff(100), exclude = {EntityNotFoundException.class, IllegalArgumentException.class,
            IllegalStateException.class})
    @Transactional
public void doSomething() {

}
```

It sounds like precedence wise we want Retry logic to have higher precedence in AOP?

**Comment by quaff** [comment]
> Interesting - for those of use waiting to go to Spring Retry 2.0.0 what is the advice to get correct operation of code like the following
> 
> ```
>     @Retryable(backoff = @Backoff(100), exclude = {EntityNotFoundException.class, IllegalArgumentException.class,
>             IllegalStateException.class})
>     @Transactional
> public void doSomething() {
> 
> }
> ```
> 
> It sounds like precedence wise we want Retry logic to have higher precedence in AOP?

 order value of EnableRetry should less than EnableTransactionManagement, like this
```
@EnableTransactionManagement(order = 0)
@EnableRetry(order = -1)
```

**Comment by artembilan** [comment]
@quaff ,

you show the configuration exactly for a new upcoming version.
For an old one this should work:

```
		@Bean
		static BeanPostProcessor retryConfigurationPostProcessor() {
			return new BeanPostProcessor() {
				@Override
				public Object postProcessBeforeInitialization(Object bean, String beanName) throws BeansException {
					if (bean instanceof RetryConfiguration) {
						((RetryConfiguration) bean).setOrder(Ordered.LOWEST_PRECEDENCE - 1);
					}
					return bean;
				}
			};
		}
```
