### ISSUE TITLE
Add proxyBeanMethods=false for @Configuration

### ISSUE THREAD

**Issue by sadew145** [spring-projects/spring-retry#222]
Hi, 

I would like to submit a commit and pull request to update @Configuration to @Configuration(proxyBeanMethods=false). In my local branch, I also updated it to the latest spring framework: 5.2.9.RELEASE in order to get this properties. If my request is considered, please check wether this version of spring framework is appropriate or I need to use a different version.

According to discussions, there is no downsides for this, but only a few benefits:
"""
1.    This will improve the performance for non-Spring Boot users
2.    This will provide hints to developers extending those classes, telling them that it's safe to use without proxying
3.    This won't break existing use cases are this is opt-in only
"""

**Comment by garyrussell** [comment]
It's not clear why that class (`RetryConfiguration`) is annotated `@Configuration` vs `@Component` (it has no `@Bean`s). @dsyer ?

Changing the Spring version would require a new major release (2.0); which is probably needed soon anyway.

**Comment by dsyer** [comment]
Good point. I think it could have always been `@Component`. But we will need a 2.0 branch soon too I hope. Maybe someone will finish the async PR.

**Comment by sadew145** [comment]
Hi, if possible, do you guys know when the update for @Component will be released? I need it because i am trying to use spring graalvm native image which require  @configuration(proxyBeanMethods=false) but there is no option for me to fix this from the outside.

**Comment by dsyer** [comment]
You can copy the code into your own project, just to get something working. I wouldn't wait for a spring-retry release, just to find out if it works. Try it and let us know how it goes.

**Comment by dsyer** [comment]
Fixed in 62d7bfe (so try with 1.3.1-SNAPSHOT).

**Comment by sadew145** [comment]
@dsyer I don't see the snapshot on maven. I need it on maven because I use spring cloud and spring retry is inside spring cloud. Is there any work around for this without copying the code? Thank you

**Comment by dsyer** [comment]
Snapshots are in repo.spring.io. If you generate a project at start.spring.io for a snapshot version of Boot it will show you the repository settings.

**Comment by sadew145** [comment]
I see it. I will test it out now. Thank you. I'll give you the update later

**Comment by sadew145** [comment]
@dsyer I get this error when using it for spring graal native image
` org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.retry.annotation.RetryConfiguration]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org
.springframework.retry.annotation.RetryConfiguration.<init>()
`

**Comment by dsyer** [comment]
Thanks for trying it. That’s normal, and nothing to do with spring-retry per se. Certainly nothing to do with this issue. You need to add that class to your reflect-config.json (which we could do automatically in spring graalvm, but it is not yet aware of spring retry).

**Comment by sadew145** [comment]
That weird because I use agent mode and RetryConfiguration exists in the generate json. Although, it doesn't generate the init() reflection. I thought it only reflect methods that are actually in the class. I'll try to specify init() in the json and see if it works. Thanks
