### ISSUE TITLE
ExponentialBackOff Needs JITTER Ability

### ISSUE THREAD

**Issue by The-Sting-Ray** [spring-projects/spring-retry#228]
The lack of a Jitter function makes the ExponentialBackOff less viable in a distributed system. There are currently no examples of manually implementing jitter with spring retry so i figured it is not implemented unless it's also not documented.

**Comment by robertmcnees** [comment]
Would using `ExponentialRandomBackOffPolicy` meet the need?  It introduces a random element to the `ExponentialBackOffPolicy`.

[doc](https://docs.spring.io/spring-retry/docs/api/current/org/springframework/retry/backoff/ExponentialRandomBackOffPolicy.html)

**Comment by garyrussell** [comment]
Closed by https://github.com/spring-projects/spring-retry/pull/376
