### ISSUE TITLE
Update source/target to 1.8+

### ISSUE THREAD

**Issue by pradeesh-kumar** [spring-projects/spring-retry#236]
The source and target level specified as 1.6 in pom.xml. This restricts contributors from using the latest features of Java. Can this be changed to 1.8 or 11?

`
\<plugin>

    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <configuration>
	    <source>1.6</source>
	    <target>1.6</target>
    </configuration>
\</plugin>
`

**Comment by garyrussell** [comment]
This will need a bump to 2.0; we can't change the java version in a minor release.

https://github.com/spring-projects/spring-retry/issues/184

**Comment by mdeinum** [comment]
Now that Spring 6 and Spring Boot 3 are in development and using Java 17 as a baseline, this might be an opportunity to start version 2.0 of spring-retry and bump the baseline to java17.

**Comment by garyrussell** [comment]
@mdeinum Yes; we have started a discussion on that internally.

**Comment by artembilan** [comment]
Has been fixed via: https://github.com/spring-projects/spring-retry/pull/286
