### ISSUE TITLE
@Recover methods not intercepted by Spring AOP advice

### ISSUE THREAD

**Issue by kriegaex** [spring-projects/spring-retry#244]
I just answered a question on StackOverflow, please read for more details and my analysis:
https://stackoverflow.com/a/67831919/1082681

The original poster of the question also published this reproducer which helped me find the root cause:
https://github.com/Nikhilgupta1891/RetryRecover

In a nutshell, Spring AOP cannot intercept the execution of a `@Recover` method because of `invocation.getThis()` instead of `invocation.getProxy()` here:

https://github.com/spring-projects/spring-retry/blob/e637911a8af4bbef372824cb9e13e3b8fa67426b/src/main/java/org/springframework/retry/annotation/AnnotationAwareRetryOperationsInterceptor.java#L159-L168

If there is no compelling reason to use the target object instead of its corresponding proxy (if any exists), please change it accordingly.

**Comment by garyrussell** [comment]
Changing it to `getProxy()` caused other problems.

I did come up with a solution, but it's a bit of a hack.

https://github.com/spring-projects/spring-retry/pull/245

**Comment by kriegaex** [comment]
I locally compiled and installed `1.3.2-SNAPSHOT` from the latest master and tested it against the sample repository provided by the other user. The aspect now kicks in as expected. Thanks for the quick fix on behalf of him.
