### ISSUE TITLE
Can we add a timeout trigger besides throwing exception

### ISSUE THREAD

**Issue by 1zg12** [spring-projects/spring-retry#251]
At the moment, seems like Throwing an exception in the method is the only trigger for the retry. Can we add a timeout trigger as well ?

So that in the annotation for example,
besides retry on SQLExpceion
`@Retryable(value = {SQLException.class}, maxAttempts = 6, backoff = @Backoff(delay = 30_000))`
it could also retry if the method not complete in 5 minutes
`@Retryable(timeout=300_000,value = {SQLException.class}, maxAttempts = 6, backoff = @Backoff(delay = 30_000))`

I think the key change on the execution is to add a timer on this line
https://github.com/spring-projects/spring-retry/blob/ebc720045ffb130d558ef9b151d5cec07bdcf81d/src/main/java/org/springframework/retry/interceptor/RetryOperationsInterceptor.java#L97

something like
```
        try {
            return Executors.newSingleThreadExecutor().submit(() -> ((ProxyMethodInvocation)this.invocation).invocableClone().proceed()).get(300_000, TimeUnit.MILLISECONDS);
        } catch (InterruptedException | ExecutionException e) {
            if(e instanceof ExecutionException)
            throw ((ExecutionException) e).getCause();
        }
```

**Comment by qianzhiyang** [comment]
maybe this timeout param should be used in biz code, rather than here

> At the moment, seems like Throwing an exception in the method is the only trigger for the retry. Can we add a timeout trigger as well ?
> 
> So that in the annotation for example, besides retry on SQLExpceion `@Retryable(value = {SQLException.class}, maxAttempts = 6, backoff = @Backoff(delay = 30_000))` it could also retry if the method not complete in 5 minutes `@Retryable(timeout=300_000,value = {SQLException.class}, maxAttempts = 6, backoff = @Backoff(delay = 30_000))`
> 
> I think the key change on the execution is to add a timer on this line
> 
> https://github.com/spring-projects/spring-retry/blob/ebc720045ffb130d558ef9b151d5cec07bdcf81d/src/main/java/org/springframework/retry/interceptor/RetryOperationsInterceptor.java#L97
> 
> something like
> 
> ```
>         try {
>             return Executors.newSingleThreadExecutor().submit(() -> ((ProxyMethodInvocation)this.invocation).invocableClone().proceed()).get(300_000, TimeUnit.MILLISECONDS);
>         } catch (InterruptedException | ExecutionException e) {
>             if(e instanceof ExecutionException)
>             throw ((ExecutionException) e).getCause();
>         }
> ```

**Comment by garyrussell** [comment]
>maybe this timeout param should be used in biz code, rather than here

Agreed; this framework is completely passive and has no active thread(s) to monitor the progress of the call; using async processing with  a future in the application is the best way to approach this use case. Bear in mind, though, that you will need some way to stop the process from completing its work, or make the work idempotent.

Closing.

**Comment by 1zg12** [comment]
> > maybe this timeout param should be used in biz code, rather than here
> 
> Agreed; this framework is completely passive and has no active thread(s) to monitor the progress of the call; using async processing with a future in the application is the best way to approach this use case. Bear in mind, though, that you will need some way to stop the process from completing its work, or make the work idempotent.
> 
> Closing.

How could the biz code/application tell whether the process running long is because it's having a high latency or because it has been going through multiple retries ?

There is already an async thread pool, we can do something like this there right ?
```
return <ThreadPool>.submit(() -> ((ProxyMethodInvocation)this.invocation).invocableClone().proceed()).get(<CONFIGURED_THRESHOLD> TimeUnit.MILLISECONDS);
```
