### ISSUE TITLE
@Retryable - Support Rethrow Instead of ExhaustedRetryException

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-retry#264]
See https://github.com/spring-projects/spring-retry/discussions/263#discussioncomment-2051710

**Comment by garyrussell** [comment]
I propose the following as a straw man:

Add 

`@AliasFor("include") Class<? extends Throwable>[] retryFor()`

`@AliasFor("exclude") Class<? extends Throwable>[] noRetryFor()`

`Class<? extends Throwable>[] noRetryNoRecoveryFor()`

All others not specified are not retriable, but go straight to recovery.

No `rethrow` attribute.

**Comment by artembilan** [comment]
Sounds like a plan.
Although if `retryFor()` is empty, it it is going to be "retry-n-recovery", like the current behavior:
```
boolean retryNotExcluded = includes.length == 0;
```
which goes to the `defaultValue` of the `SimpleRetryPolicy`.

I guess we can set a new `RetryContext.NO_RECOVERY` attribute in the `SimpleRetryPolicy` for the `noRetryNoRecoveryFor` to avoid polluting `RetryTemplate` API...
The `null` value for those exceptions should be OK in the `Map<Class<? extends Throwable>, Boolean> retryableExceptions` as an indicator for a third state.
