### ISSUE TITLE
Is there a way to use @Retryable with XML configuration?

### ISSUE THREAD

**Issue by manish-in-java** [spring-projects/spring-retry#27]
I have a very large application that uses XML configuration throughout.  To some of the operations we would like to add the `@Retryable` annotation so that these can be retried a few times before giving up fully.

The documentation suggests that `@Retryable` is activated using `@EnableRetry` on a Java configuration class.  Since we do not use Java based configuration, is there a way to enable `@Retryable` using XML configuration?

**Comment by nikhil-thakur** [comment]
Hey Manisha. I configured swagger the same was you have, I dont see any documentation other than just a jason output on the browser when I go to localhost:8080/api-docs. whats the work around this issue?

**Comment by rince1013** [comment]
I have this same question

**Comment by garyrussell** [comment]
I just tested with this...

	<context:annotation-config />

	<aop:aspectj-autoproxy />

	<bean class="org.springframework.retry.annotation.RetryConfiguration" />

...and it worked ok for me (you need AspectJ on the classpath).

**Comment by garyrussell** [comment]
Of course, you can also add

    @Configuration
    @EnableRetry
    public class MyClassWithARetryable {
    ...

to just one of your beans and then you only need

    <context:annotation-config />

(but you still need AspectJ on the classpath).

**Comment by manish-in-java** [comment]
Thanks Gary, this is perfect.

**Comment by ranadeep-sharma** [comment]
Thanks @garyrussell . This was truly helpful. Works like a charm.

**Comment by aagarwal9907** [comment]
what version of spring is the above configuration working for . i tired it on 1.3.0. and this is not working. 
any idea if i need to change spring core version.

**Comment by ranadeep-sh** [comment]
Spring Core 4.x
