### ISSUE TITLE
Expose BackOffPolicy creation logic through a BackOffPolicyBuilder

### ISSUE THREAD

**Issue by tomazfernandes** [spring-projects/spring-retry#276]
This issue is to propose exposing value-based `BackOffPolicy` creation logic, currently in [this part](https://github.com/spring-projects/spring-retry/blob/14c7217bbc70c81ebd5e0ea045410f7e69f788c4/src/main/java/org/springframework/retry/annotation/AnnotationAwareRetryOperationsInterceptor.java#L381) of the `AnnotationAwareRetryOperationsInterceptor` class, through a `BackOffPolicyBuilder` class, so other `Spring` projects and perhaps end users can use it, keeping consistency throughout the projects and avoiding duplicated logic.

**Context**

When `Spring Kafka`'s [Non-blocking retries feature](https://docs.spring.io/spring-kafka/reference/html/#retry-topic) was developed, the `Spring Retry` project wasn't getting many releases. As we wanted to leverage some of `Spring Retry`'s functionality, such as the `@BackOff` annotation and the `BackOffPolicy` interface and implementations, the solution was to duplicate the `BackOffPolicy` creation logic in `Spring Kafka`, as can be seen [here](https://github.com/spring-projects/spring-kafka/blob/f83fc4b11eed2708a488227bccc63d93dc16c3ed/spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopicAnnotationProcessor.java#L158).

Now that we're in the process of [adding auto configuration](https://github.com/spring-projects/spring-boot/issues/28450) capabilities to the feature, we need to be able to access this logic in `Spring Boot` as well. After discussing this matter with @wilkinsona and @artembilan, considering the `Spring Retry` project is now getting more support,  it seems like the right approach would be to make this logic accessible through a `BackOffPolicyBuilder` and use it both in `Spring Kafka` and `Spring Boot` projects.

If that does look like the right approach I can provide a PR, if that's ok.

Thanks, and I'm really glad to see this project under more active support again, it's a very useful and well-thought project.

**Comment by artembilan** [comment]
That's what we have discussed, @tomazfernandes .

If you really have something in mind, feel free to raise a PR and I'll review it shortly.

Thanks

**Comment by tomazfernandes** [comment]
Sure @artembilan. As this is a different project I wanted to provide some context to everyone else who might see this issue. I've opened the PR just now.

Thanks
