### ISSUE TITLE
Is it possible to add persistence support

### ISSUE THREAD

**Issue by chenqimiao** [spring-projects/spring-retry#279]
The retry context will be lost, if we restart application, so I wonder if it is possible to add a persistence capability, after restart application, the application still get the retry context from disk or other db.

**Comment by artembilan** [comment]
The `RetryTemplate` has this option:
```

	/**
	 * Public setter for the {@link RetryContextCache}.
	 * @param retryContextCache the {@link RetryContextCache} to set.
	 */
	public void setRetryContextCache(RetryContextCache retryContextCache) {
		this.retryContextCache = retryContextCache;
	}
```

So, there is just need to implement a persistent store `RetryContextCache`.
I doubt an implementation details may belong to this project: it is so lightweight that it does not have dependencies on other data-specific projects.
However it doesn't look like a `RetryContext` abstraction is is so ready for persistence...
