### ISSUE TITLE
1.1.2 Dependencies not complete.

### ISSUE THREAD

**Issue by drekka** [spring-projects/spring-retry#30]
I've included 1.1.2 into a gradle project using this:

    compile "org.springframework.retry:spring-retry:1.1.2.RELEASE"

However when I attempted to run the war file I get this exception:

    Caused by: java.lang.ClassNotFoundException: org.aspectj.lang.annotation.Around
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_45]
    ....

It appears that there are dependencies which have not been resolved or downloaded. Is there something missing from the POM?

**Comment by garyrussell** [comment]
`spring-retry` has no runtime dependencies on AspectJ.

Perhaps something else in your application is referencing it?

**Comment by ek-ex** [comment]
I have the same problem as drekka, it's a completely new project just to test spring-retry with only spring retry and spring boot.

**Comment by garyrussell** [comment]
AspectJ is only needed if you are using `@Retry` annotations so the project doesn't have it as a hard dependency because it's not needed if you are programmatically configuring or using XML.

**Comment by drekka** [comment]
Given that annotations are the way things are going, I would suggest that making AspectJ a dependency would be a good idea. XML configs are old school (and a pain to maintain) and programmatic is what people do when they need something not provided by out of the box annotations.

**Comment by jonpeterson** [comment]
FWIW, I agree with @drekka.  I came here with the same issue.  Now I need to go figure out what version of AspectJ to manually include.

**Comment by selimok** [comment]
I agree with @drekka too. 

My workaround was to add following dependency into my pom:

```
<dependency>
	<groupId>org.springframework</groupId>
	<artifactId>spring-aspects</artifactId>
</dependency>
```

**Comment by Ghilteras** [comment]
I tried adding both `spring-aspects` and `spring-aop` together with `aspectjtools` `aspectjrt` and `aspectjweaver` but I keep getting 
`java.lang.ClassNotFoundException: org.aspectj.lang.annotation.Pointcut`
same thing with `spring-boot-starter-aop` so I'm not sure what to do next at this point

The relevant part of my Spring xml looks like this
```xmlns:aop="http://www.springframework.org/schema/aop"
      xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
                           http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context.xsd
                           http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop-3.0.xsd
                           http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util.xsd"
       default-init-method="initialize" default-destroy-method="destroy">
    <context:annotation-config />

    <aop:aspectj-autoproxy />

    <bean class="org.springframework.retry.annotation.RetryConfiguration" />
```

I am just trying to be able to use a @Retryable annotation before one of my methods

**Comment by dsyer** [comment]
Sound like you need to read up on Spring AOP (and probably stop using `<aop:aspectj-autoproxy/>`). Anyway this is kind of unrelated to the original (closed) issue.

**Comment by Ghilteras** [comment]
@dsyer what are the AOP dependencies I need to pull in my `pom.xml` to use `1.2.4` version of `spring-retry` ?
