### ISSUE TITLE
@Retryable doesn't seem to support usage as a meta-annotation (composition/"inheritance")

### ISSUE THREAD

**Issue by erizzo** [spring-projects/spring-retry#301]
I have a code base with several nearly-identical usages of `@Retryable`, all driven by the same configuration values. So I created a new annotation that's annotated with ("inherits") `@Retryable`, like this:

```java
@Documented
@Retention(RUNTIME)
@Target({ TYPE, METHOD })
@Retryable(
	include = RestClientException.class,
	maxAttempts = 5,
	backoff = @Backoff(delay = 1000, multiplier = 3)
	)
public @interface RESTClientRetry {

	@AliasFor(annotation = Retryable.class, attribute = "listeners")
	String[] listeners() default {};

	@AliasFor(annotation = Retryable.class, attribute = "include")
	Class<? extends Throwable>[] include() default {};

	@AliasFor(annotation = Retryable.class, attribute = "maxAttemptsExpression")
	String maxAttemptsExpression() default "";

	@AliasFor(annotation = Retryable.class, attribute = "backoff")
	Backoff backoff() default @Backoff();
}
```

This works as expected, except for when I want usages of this annotation to use their own listeners. Usage is like this:
```java
@RESTClientRetry(listeners = "retryLoggerBean1")
```

In an application where there are several `RetryListener` beans (named `retryLoggerBean1`, `retryLoggerBean2`, etc), they are _all_ getting called for _every_ method that's annotated with `RESTClientRetry`, even though each annotation specifies its own `listeners`.

Using the debugger, I see that when `AnnotationAwareRetryOperationsInterceptor` is invoked, the `Retryable` object has an empty value for `listeners`. So it seems like that interceptor is not supporting annotation "inheritance" (composition). Without any annotation-specific listeners, it's falling back to the global set of listeners, which explains why I'm seeing them _all_ invoked for _every_ method.

Have I done something wrong? Is this a known limitation or bug with the interceptor, or is there another way to wrap `@Retryable` with my own annotation and still le individual usage define which listener to use?

**Comment by fengkongling** [comment]
ok，亲~~~

**Comment by artembilan** [comment]
This works for me as intended:
```
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.ElementType.TYPE;
import static java.lang.annotation.RetentionPolicy.RUNTIME;
import static org.junit.Assert.assertEquals;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import org.junit.Test;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.annotation.AliasFor;
import org.springframework.retry.RetryCallback;
import org.springframework.retry.RetryContext;
import org.springframework.retry.RetryListener;
import org.springframework.retry.annotation.Backoff;
import org.springframework.retry.annotation.EnableRetry;
import org.springframework.retry.annotation.Retryable;
import org.springframework.retry.listener.RetryListenerSupport;

public class EnableRetryWithListenersTests {

	@Test
	public void overrideListener() {
		AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(
				TestConfigurationMultipleListeners.class);
		ServiceWithOverriddenListener service = context.getBean(ServiceWithOverriddenListener.class);
		service.service();
		assertEquals(1, context.getBean(TestConfigurationMultipleListeners.class).count1);
		assertEquals(0, context.getBean(TestConfigurationMultipleListeners.class).count2);
		context.close();
	}


	@Configuration
	@EnableRetry
	protected static class TestConfigurationMultipleListeners {

		private int count1 = 0;

		private int count2 = 0;

		@Bean
		public ServiceWithOverriddenListener service() {
			return new ServiceWithOverriddenListener();
		}

		@Bean
		public RetryListener listener1() {
			return new RetryListenerSupport() {
				@Override
				public <T, E extends Throwable> void close(RetryContext context, RetryCallback<T, E> callback,
						Throwable throwable) {
					count1++;
				}
			};
		}

		@Bean
		public RetryListener listener2() {
			return new RetryListenerSupport() {
				@Override
				public <T, E extends Throwable> void close(RetryContext context, RetryCallback<T, E> callback,
						Throwable throwable) {
					count2++;
				}
			};
		}

	}

	protected static class ServiceWithOverriddenListener {

		private int count = 0;

		@MyRetryable(listeners = "listener1")
		public void service() {
			if (count++ < 2) {
				throw new RuntimeException("Planned");
			}
		}

		public int getCount() {
			return count;
		}

	}

	@Retention(RUNTIME)
	@Target({ TYPE, METHOD })
	@Retryable(backoff = @Backoff(delay = 1000))
	@interface MyRetryable {

		@AliasFor(annotation = Retryable.class, attribute = "listeners")
		String[] listeners() default {};

	}

}
```

According to your report both of those `RetryListener` beans has to be called independently of the `listeners` value in our extended annotation. But it is not: it really calls only the `listener1`.
Tested against the latest `spring-retry-1.3.3`.

**Comment by artembilan** [comment]
Well, then there is no way for you to support that feature. 
If you cannot upgrade this dependency (which is fully transparent and does not need anything else), then you cannot use a meta-annotation feature and have to stay with only `@Retryable` everywhere for time being.

**Comment by erizzo** [comment]
I spoke too soon - your test passes with 1.3.3 but my own code still shows both listeners being invoked for every @Retryable method call.

**Comment by artembilan** [comment]
Then you have something else in your code which you don't show to us.
Perhaps several of your `@RESTClientRetry` are called at the same time.

It would be great if you could share with us a simple project to reproduce and play with.

**Comment by garyrussell** [comment]
1.2.x used `AnnotationUtils.findAnnotation()` (it was written long before `@AliasFor` was added).

1.3.x uses `AnnotatedElementUtils.findMergedAnnotation()` which is why it works now.

**Comment by erizzo** [comment]
I was fighting with Maven (it's such a pain in the rear end sometimes). Since I'm working with 2 different in-house libraries, which reference various Spring dependencies, including starters and spring--boot-dependencies, I had to override the right maven property to get 1.3.3 truly included in the application I'm working on.
Now that I've done the Maven dance, my code is working as expected with 1.3.3, just like the unit test above.
I'll close this issue, understanding that the problem is an old version of spring-retry and @garyrussell explained exactly why in his comment above.
