### ISSUE TITLE
retry only accepts exception; it would be nice if we can retry with another data type

### ISSUE THREAD

**Issue by praveeno-dev** [spring-projects/spring-retry#308]
retry only accepts exception; it would be nice if we can retry with another data type

**Comment by artembilan** [comment]
This just does not make sense from the retry pattern perspective: https://docs.microsoft.com/en-us/azure/architecture/patterns/retry.

So, if you think that you need to retry on something which is not an exception, consider to throw a custom exception of that data.

Or... Perhaps you have in mind something what is called **Repeat** pattern: https://docs.spring.io/spring-batch/docs/current/reference/html/repeat.html#repeat.
And then that one is already out of this project scope.

**Comment by praveeno-dev** [comment]
thanks for the response @artembilan !
