### ISSUE TITLE
EnableRetry annotation using deprecated convention-based annotation attribute overrides

### ISSUE THREAD

**Issue by OriSchmitz** [spring-projects/spring-retry#327]
When deploying a service using Spring framework 6.0 and Spring retry 2.0.0 this message is logged:

`Support for convention-based annotation attribute overrides is deprecated and will be removed in Spring Framework 6.1. Please annotate the following attributes in @org.springframework.retry.annotation.EnableRetry with appropriate @AliasFor declarations: [proxyTargetClass]`

And indeed `EnableRetry` contains `proxyTargetClass` without the `@AliasFor` annotation.

**Comment by gaofengIt** [comment]
您好，我已经收到您的邮件，将尽快给您回复。

**Comment by garyrussell** [comment]
It is already fixed; https://github.com/spring-projects/spring-retry/pull/322 and will be in 2.0.1 when it is released (not currently scheduled but should be available early next year.
