### ISSUE TITLE
Spring boot 3 warning: annotate the following attributes in @org.springframework.retry.annotation.EnableRetry with appropriate @AliasFor declarations: [proxyTargetClass]

### ISSUE THREAD

**Issue by christophers88** [spring-projects/spring-retry#331]
Using the latest version of spring-retry with Spring Boot 3 generates the following warning in the output log at startup time.

> Support for convention-based annotation attribute overrides is deprecated and will be removed in Spring Framework 6.1. Please annotate the following attributes in @org.springframework.retry.annotation.EnableRetry with appropriate @AliasFor declarations: [proxyTargetClass]

**Comment by artembilan** [comment]
Has been fixed with this: https://github.com/spring-projects/spring-retry/pull/322
