### ISSUE TITLE
RetryListenerSupport#onError  is  triggered with an unexpected Exception

### ISSUE THREAD

**Issue by lianyiwuming** [spring-projects/spring-retry#338]
I expect retry on exception type ZabbixAuthException，but got  RetryListenerSupport#onError invoked by exception type RuntimeException. 

idea  debug like blow:
  
<img width="884" alt="1" src="https://user-images.githubusercontent.com/23331492/233336142-2e45578c-a945-458d-a7c5-c2c572eb79ec.png">

**Comment by artembilan** [comment]
That's correct. The logic there is like this:

```
catch (Throwable e) {

					lastException = e;

					try {
						registerThrowable(retryPolicy, state, context, e);
					}
					catch (Exception ex) {
						throw new TerminatedRetryException("Could not register throwable", ex);
					}
					finally {
						doOnErrorInterceptors(retryCallback, context, e);
					}

					if (canRetry(retryPolicy, context) && !context.isExhaustedOnly()) {
```

So, the `RetryListener#onError()` is always called for any exception, even if it is going to be rejected by the next `canRetry()`.
And that is even mentioned in its Javadocs:
```
	/**
	 * Called after every unsuccessful attempt at a retry.
	 * @param context the current {@link RetryContext}.
	 * @param callback the current {@link RetryCallback}.
	 * @param throwable the last exception that was thrown by the callback.
	 * @param <T> the return value
	 * @param <E> the exception to throw
	 */
	default <T, E extends Throwable> void onError(RetryContext context, RetryCallback<T, E> callback,
			Throwable throwable) {
	}
```

You probably need to move your auth token refresh logic into a custom `RetryPolicy`: if a delegate returns true from its `canRetry()`., you perform auth refresh and return that `true` for the `RetryTemplate` to move on to the next attempt.

We may think about something like a new `RetryListener.beforeNextRetry()` interception hook, but that's fully different story from what you have asked and needs a team discussion.

**Comment by lianyiwuming** [comment]
Ok，I had checked the logic.   It's just a little  confusion with retryOn exception and RetryListenerSupport#onError  exception.
