### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by lufei66666** [spring-projects/spring-retry#339]
why java.lang.NullPointerException: null
	at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.getDelegate(AnnotationAwareRetryOperationsInterceptor.java:161)?

use spring-retry:1.2.5.RELEASE

**Comment by snicoll** [comment]
@lufei66666 it's hard to provide support with a 2 lines stack trace. Can you please share a small sample that reproduces the NPE? You can share that with us as a zip attached to this issue or by sharing a link to a GitHub repository.

**Comment by artembilan** [comment]
That version is out of support. Please, consider to upgrade at least to `1.3.4`.
And yes: simple code to reproduce would be great.

There is some fix for that class in `1.2.x`, but it was never released: https://github.com/spring-projects/spring-retry/commit/b279131e4048863bd094b745f7f0e1cfce2d2fb6.

So, yeah, better to upgrade to the latest supported version - and your problem might go away.

**Comment by artembilan** [comment]
Has been fix in up-to-date version this or other way.
