### ISSUE TITLE
SpringCloud gateway route retry does not work

### ISSUE THREAD

**Issue by michaelwangwangwang** [spring-projects/spring-retry#356]
When a service instance goes offline suddenly, a connection refuse error will be reported from the request initiated by the gateway to the service instance

**Comment by artembilan** [comment]
Please, consider to share much more info and justify what exactly is needed to be fixed on Spring Retry side.
It looks like your question is more about Spring Cloud Gateway, but before moving there we need some proofs.
For now there is nothing we can hook in to proceed.

Thanks for understanding.

P.S. I prefer to have questions like this in the community forum like StackOverflow.
The GH issues are really for issues or bugs.

**Comment by michaelwangwangwang** [comment]
> 请考虑分享更多信息，并证明在 Spring Retry 方面研究实际上需要修改什么。 看来你的问题更多是关于 Spring Cloud Gateway，但在移动到那里之前我们需要要一些证明。 目前，我们无法继续进行任何操作。
> 
> 感谢您的理解。
> 
> PS 我更喜欢像 StackOverflow 这样的社区论坛中提出这样的问题。 GH 问题实际上是针对问题或错误的。

https://github.com/spring-cloud/spring-cloud-gateway/issues/2738
