### ISSUE TITLE
Retry @Recover

### ISSUE THREAD

**Issue by todorolev** [spring-projects/spring-retry#370]
The business logic in the @Recover methods may fail in some cases. For example:
 - when the method attempts to recover state from before calling the @Retryable method
 - when the method calls an API, e.g. over HTTP
 - when the method sends an event, e.g. for audit purposes
 - when the method attempts to rollback a DB change

In such cases a @Recover method may benefit from a retry mechanism on its own.

**Comment by garyrussell** [comment]
The `@Recover` method is a last chance behavior; if it fails, the exception is thrown to the caller.

You can put a `try {...} catch (...) {...}` block in the recoverer to handle exceptions; if you want a nested retry, then simply call another `@Retryable` method (in another bean), or use a `RetryTemplate` in the `@Recover` method.

```java
@Recover ....(Exception ex, SomeData data) {
    someOtherBean.retryableRecover(ex, data);
}
```

Given this simple work around, I don't think it is worth complicating the framework further.

**Comment by todorolev** [comment]
Thanks! This makes sense and probably my understanding of the @Recover method was wrong. My expectation was that it was OK to add some rollback logic in the @Recover method (in order to rollback the effects of the @Rretryable) and if that fails, then throw an exception. Overall right now to me it looks like spring-retry is not intended to work with state-changing logic.
