### ISSUE TITLE
Backport: Introduce order for `@EnableRetry`

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-retry#372]
Backport of https://github.com/spring-projects/spring-retry/pull/333

**Comment by quaff** [comment]
@artembilan I've created https://github.com/spring-projects/spring-retry/pull/373

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-projects/spring-retry/commit/cbccb586132a11d07df1e5347933f4593bb93bf4

**Comment by snicoll** [comment]
1.3.x is no longer supported on OSS.

**Comment by fengkongling** [comment]
ok，亲~~~
