### ISSUE TITLE
Can not inject java bean when using @Retryable in spring amqp RabbitLisener

### ISSUE THREAD

**Issue by adorabled4** [spring-projects/spring-retry#378]
when using `@Retryable` , it seems that spring can't  ject java bean by `@Resource` , although I can see the bean in IDEA 's UI.
![image](https://github.com/spring-projects/spring-retry/assets/96526641/364e7f11-9b9c-4b66-976d-d33886769047)

![image](https://github.com/spring-projects/spring-retry/assets/96526641/bbba4216-a584-46fb-b25d-9730430b1fd6)

![1693153989736](https://github.com/spring-projects/spring-retry/assets/96526641/1b1b3c58-ea4b-4054-8f8f-bfce6c54bdf1)

and when cancel using  `@Retryable` , program can run correctly

![1693154388327](https://github.com/spring-projects/spring-retry/assets/96526641/507184f8-6b5d-41d3-b826-f7c019d3c0c8)

![image](https://github.com/spring-projects/spring-retry/assets/96526641/f1da27b1-8bcc-424b-ba56-105bf6d5115a)

my environments are as following
- springboot : 2.5.6
- spring-rabbit : 2.3.11
- spring retry : 1.3.1

**Comment by snicoll** [comment]
@adorabled4 please don't paste screenshots here. Can you rather please share a small sample we can run ourselves? A zip file attached to this issue or a project pushed to a separate GitHub repository. Thanks!

**Comment by adorabled4** [comment]
> @adorabled4 please don't paste screenshots here. Can you rather please share a small sample we can run ourselves? A zip file attached to this issue or a project pushed to a separate GitHub repository. Thanks!

Thanks for answer , I will try to make a demo repo to replicate this bug. Please wait a moment.

**Comment by adorabled4** [comment]
I've replicate the bug successfully , please visit [dem0828](https://github.com/adorabled4/dem0828) for detail.
By the way, I found that just **change the access to the consumer method to public** can solve this bug , which is private on above code.

---
You can visit [dem0828](https://github.com/adorabled4/dem0828)  and found `com.dhx.dem0828.mq.MessageConsumer#demoListener` , change it to private . Then debug application  , visit `http://localhost:8080/test/send` .

**Comment by garyrussell** [comment]
Spring Boot 2.5.x is no longer supported: https://spring.io/projects/spring-boot#support

spring-retry `@Retryable` only supports `public` methods; this is because, in normal circumstances, the method is called from another `@Bean`.

**Comment by adorabled4** [comment]
> Spring Boot 2.5.x is no longer supported: https://spring.io/projects/spring-boot#support
> 
> spring-retry `@Retryable` only supports `public` methods; this is because, in normal circumstances, the method is called from another `@Bean`, and therefore must be public.
> 
> The error is some side-effect of using CGLIB, which can't override private methods.

🤩🤩🤩thank you very much. 
 I've try to make a CGLIB demo to comprehend it.

**Comment by artembilan** [comment]
That is expected behavior. The `@Retryable` makes a proxy around the method to call and that indeed has to be `public` to be available for proxy library.

Closed as `Invalid`.
