### ISSUE TITLE
Restore the interrupted thread status in the provided backoff policies

### ISSUE THREAD

**Issue by mlichtblau** [spring-projects/spring-retry#386]
It is good practice to restore the interrupted flag of the current thread when `InterruptedException` cannot be thrown.

From Java Concurrency in Practice[^1]:
> Sometimes you cannot throw `InterruptedException`, for instance when your code is part of a `Runnable`. In these situations, you must catch `InterruptedException` and restore the interrupted status by calling interrupt on the current thread

The provided backoff policies (e.g. `FixedBackOffPolicy`, `ExponentialBackOffPolicy`) throw a `BackOffInterruptedException` without restoring the flag.

Do you think it is possible to restore the flag before throwing the runtime exception?
I can open a PR.

Thank you!

[^1]: [Google Books](https://books.google.de/books/about/Java_Concurrency_in_Practice.html?id=mzgFCAAAQBAJ)

**Comment by garyrussell** [comment]
Good catch, yes, this is a bug. A PR would be welcome.
