### ISSUE TITLE
Expose the number of max attempts to the retry context for all policies

### ISSUE THREAD

**Issue by e-ivaldi** [spring-projects/spring-retry#395]
It is sometimes useful to be aware, within a retry context, whether the current attempt is the last attempt when using a 'maximum number of attempts before failure' type of retry policy.

Following up on this [discussion](https://github.com/spring-projects/spring-retry/discussions/362) I am opening a small PR to add that type of support to spring-retry.

In order to achieve the desired result, for all policies, a new attribute is going to be added to the context named "context.max-attempts" that will contain the number of max attempts set in the policy, if any, or -1 otherwise.

The PR won't provide extra support to read and parse the attribute value via ad-hoc methods added to the retry contexts themselves.

PR link: https://github.com/spring-projects/spring-retry/pull/396

**Comment by deathcoder** [comment]
@garyrussell i saw you were involved in the discussion, i'm just not familiar with the process here, how do can we get the pr reviewed?

**Comment by garyrussell** [comment]
Someone just has to pick it up; I have been out sick the last couple of weeks; as such, I have a huge backlog so I may not get to this for a while.
