### ISSUE TITLE
stateless retry always throws original exception on exhaustion

### ISSUE THREAD

**Issue by zyro23** [spring-projects/spring-retry#40]
this is maybe more a question than a real issue but i would like to know what is the expected behavior.

the readme states that
> Simple implementations will just throw RetryExhaustedException which will cause any enclosing transaction to be rolled back

but for a stateless retry, that is not the behavior i am seeing (always original exception thrown).

`handleRetryExhausted` is invoked correctly, with `state` being `null` (ok, i guess, because the retry is stateless). but then, it looks like always the original exception is thrown back to the user, never wrapped in an `ExhaustedRetryException`. that is because `thrown()` is not invoked but instead just `throw wrapIfNecessary(context.getLastThrowable());` (https://github.com/spring-projects/spring-retry/blob/master/src/main/java/org/springframework/retry/support/RetryTemplate.java#L467)

thanks for clarification!

**Comment by garyrussell** [comment]
Looks like an error in the README - the Javadoc just above the line you linked to defines the behavior you observe.

**Comment by zyro23** [comment]
ah ok, thanks :)
but then currently no way to make a stateless retry throw an `ExhaustedRetryException` by default, right?
in some cases it would be useful to be able to distinguish that cause from the original exceptions - but if thats really needed the wrapping can be handled manually in a recoverer as well, i guess...

**Comment by garyrussell** [comment]
Yeah, I agree it's a bit inconsistent but, as you say, you can do it via a simple recoverer.

**Comment by dsyer** [comment]
Thanks, fixed in c8f2d07.
