### ISSUE TITLE
Issue with aspectjweaver  dependency used since version 2.0.0

### ISSUE THREAD

**Issue by staniakm** [spring-projects/spring-retry#406]
There is an issue with delay when multiplierExpression is used. It starts since version 2.0.0. I've found that issue probably comes from aspectjweaver. 
I have simple spring service writen in kotlin and really simple test for it. Test will fail with spring-retry 2.0.0 up to 2.0.4 but will pass for version 1.3.4
After bumping aspectjweaver  from 1.9.20 to 1.9.20.1 building spring-retry locally problem was solved and test has passed

```@Service
class RetiedService() {
    @Retryable(IllegalArgumentException::class,
        backoff = Backoff(
            delayExpression = "\${setup.delay}",
            multiplierExpression = "\${setup.multiplier}",
            ),
        maxAttempts = 4)
    fun toBeRetried() {
        println ("${Instant.now()} Running method")
        willThrow()
    }

    private fun willThrow() {
        throw IllegalArgumentException("some exception")
    }
}
```

Properties
```
setup.delay=500
setup.multiplier=2.0
```
And test
```
@SpringBootTest
class Demo3ApplicationTests {

    @Autowired
    lateinit var service: RetiedService

    @Test
    fun contextLoads() {
        val time = measureTimeMillis {
            assertThrows<IllegalArgumentException> {
                service.toBeRetried()
            }
        }
        println(time)
        assert(time > 3500)
    }
}
```

**Comment by artembilan** [comment]
So, if you confirm that updating to the latest AspectJ `1.9.20.1` fixes the problem, may  that is what enough to do in this project and the fix will be available in the next version we will plan to release this week?
If that a case, feel free to contribute such a fix.
Maybe your simple test would be great to have as an addition.

Thanks
