### ISSUE TITLE
put GAV in docs

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-retry#418]
could you please put your group artifact version (or at least the first 2) in the docs somewhere? I find myself spending way too much time looking for them.

https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#spring-cloud-circuit-breaker

would be great, https://docs.spring.io/spring-cloud-circuitbreaker/reference/index.html

https://docs.spring.io/spring-cloud-circuitbreaker/reference/spring-cloud-circuitbreaker-spring-retry.html

come on, even the readme in this repo.

**Comment by xenoterracide** [comment]
I finally see it at the bottom here https://spring.io/projects/spring-cloud-circuitbreaker#overview

**Comment by artembilan** [comment]
I'm sorry, what is the question exactly for Spring Retry?
Maybe your concern better would really live in that https://github.com/spring-cloud/spring-cloud-circuitbreaker project?

**Comment by xenoterracide** [comment]
maybe? I mean the readme here doesn't say what it is either. I'm generally frustrated with spring as a whole on this topic (what Group Artifact is this in!)

**Comment by artembilan** [comment]
I see, so you mean something like this: https://github.com/spring-projects/spring-integration#installation-and-getting-started should be present in the README for this project?
Unfortunately, different projects under different repositories and handled different teams.
So, it might be better to raise respective issue exactly over there.

I'm OK to fix it here, but let's see first that we are on the same page!

P.S. I'm not sure though why rude language should be used for this kind of discussion.
