### ISSUE TITLE
Does it support springboot3? It seems that it cannot be used under springboot3.

### ISSUE THREAD

**Issue by aozeyu** [spring-projects/spring-retry#419]
@rmorgan @joshlong

**Comment by artembilan** [comment]
@aozeyu ,

Please, share much more info what the problem you are facing.
Perhaps you are using very old Spring Retry version which indeed is not compatible with Spring Boot 3.x.
For that purpose we have current `2.0.5`, which is really managed by latest Spring Boot: https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-dependencies/build.gradle#L1599.

So, technically, you just need to add `implementation 'org.springframework.retry:spring-retry'` dependency into your Spring Boot-based project and the proper version is going to be managed from there.
Also: if you use `@Retriable` annotation, you have to include: `spring-boot-starters:spring-boot-starter-aop` dependency.
And one more: Spring Boot does not auto-configure retry for us, so you have to add `@EnableRetry` manually on one of your configuration class.

Sorry, if this info is not what you'd expect to here: just speculating from whatever you gave us so far.

**Comment by aozeyu** [comment]
Got it, I've solved it, thank you very much for your reply @artembilan
