### ISSUE TITLE
Wrong method recommended for build.gradle?

### ISSUE THREAD

**Issue by banan314** [spring-projects/spring-retry#423]
You recommend adding ` runtime('org.springframework.boot:spring-boot-starter-aop')` as a dependency to the project, but then I get _No candidates for method call runtime_. Did you mean
```
runtimeOnly 'org.springframework.boot:spring-boot-starter-aop'
```
?

**Comment by gaofengIt** [comment]
您好，我已经收到您的邮件，将尽快给您回复。

**Comment by artembilan** [comment]
That was written long time ago when there was no `runtimeOnly` in Gradle.
Feel free to contribute the fix for that docs: https://github.com/spring-projects/spring-retry?tab=readme-ov-file#-additional-dependencies !

Thanks
