### ISSUE TITLE
Missing aspectjweaver dependency

### ISSUE THREAD

**Issue by stepio** [spring-projects/spring-retry#44]
Good evening, gentlemen.

Correct me if I'm wrong, but seems that "aspectjweaver" is a mandatory dependency to use spring-retry with annotations.

But when I generated project with spring-retry at "start.spring.io", this dependency was not included. In my opinion it's confusing - annotations are are one of the most common instruments in Spring, so it's seems natural for me to use them.

**Comment by garyrussell** [comment]
I guess the reasoning is that for users that don't use annotations, the dependency is unnecessary.

Whichever choice is made will cause distress to the other half of users 😄

**Comment by stepio** [comment]
That means that as of now the main (recommended) option is not to use annotations. If not, current behaviour spoils the idea of using "start.spring.io" to generate project, which works out of the box.

Maybe it's not an issue for spring-retry itself, but a possible improvement of the above mentioned wizard.

Or you still think that current behaviour is fine as is?

**Comment by garyrussell** [comment]
You could try opening an issue against boot and reference this one - it's not that XML is "preferred" over annotations, just that it's a bit antisocial to pull in an unnecessary dependency for folks that don't need it.

**Comment by garyrussell** [comment]
Sorry for the delay in replying.

You could try opening an issue against the intializr and reference this one - it's not that XML is "preferred" over annotations, just that it's a bit antisocial to pull in an unnecessary dependency for folks that don't need it.

**Comment by jonpeterson** [comment]
Could the project be split into two modules?  `spring-retry` and `spring-retry-annotations` (the later depending on the former)?  The annotation module would include the annotations themselves as well as dependencies on the aspectjweaver?
