### ISSUE TITLE
Unable to find documentation for spring-retry project

### ISSUE THREAD

**Issue by amirensit** [spring-projects/spring-retry#446]
Hello.
Is it possible to add **spring-retry** project to list of documentation for spring projects ?

Best regards

**Comment by artembilan** [comment]
There is no documentation for this project, just its README.
Since GitHub is very popular and visible for community, we find it as enough to have it this way for this plain one-module project.
We will have more discussion on the matter internally...

**Comment by amirensit** [comment]
Okey.
