### ISSUE TITLE
Use RetryListener with @Retryable

### ISSUE THREAD

**Issue by stepio** [spring-projects/spring-retry#45]
Hi,

I'd like to be able to register `RetryListener` for my `RetryOperationsInterceptor`, which I use as a configuration for `Retryable` annotation.

But as I see in the [docs](http://docs.spring.io/spring-batch/reference/html/retry.html), such option is available only for `RetryTemplate`.

Am I correct? Any plans to support `Retryable` as well?

**Comment by stepio** [comment]
Let me also describe the use case if you're interested.

I love the idea of Spring Actuator and I want to track the stats of retrying as well - just to understand how effective is this feature in my case, how often there are any issues, etc.

So maybe it's also a possible feature for spring-retry itself - like the cache metrics and tomcat sessions' metrics.

**Comment by eileenh** [comment]
I was just looking into a similar thing - it looks like it is possible to create a RetryListener and hook it up using a RetryOperationsInterceptor. I created a RetryListener, attached it to a RetryTemplate, and then passed that template in to the RetryOperationsInterceptor:

`RetryOperationsInterceptor myInterceptor() {
        RetryTemplate template = new RetryTemplate();
        RetryListener listener = new RetryListener() {
            ...
        };
        template.registerListener(listener);

        return RetryInterceptorBuilder.stateless().retryOperations(template).build();
}`

**Comment by stepio** [comment]
Thanks, @eileenh ,

In my case I've already switched to `RetryTemplate` usage:
1. Also fits my case with minimum code updates.
2. I was able to add the needed `RetryListener `
3. No aspects.

**Comment by stepio** [comment]
Closing issue due to the lack of interest from maintainers.
