### ISSUE TITLE
EnableRetryWithBackoffTests is flaky

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-retry#456]
```
EnableRetryWithBackoffTests.randomExponential:77 [Wrong periods: %s[1000, 1124]]
Expecting value to be true but was false
```

**Comment by artembilan** [comment]
According to the report it turns out that our random logic in the `ExponentialRandomBackOffPolicy`:
```
next = (long) (next * (1 + r.nextFloat() * (getMultiplier() - 1)));
```
Accidentally ended up with with `1`.
Therefore `1000 * 1 = 1000`  😄 

Fixing test respectively to include that possibility.
