### ISSUE TITLE
Version in pom.xml contains "${revision}"

### ISSUE THREAD

**Issue by Kuba15** [spring-projects/spring-retry#474]
Hello!

In the pom/xml provided in the jar file or available on mvnrepository.com, the <version> tag contains ${revision}:

```
<groupId>org.springframework.retry</groupId>
<artifactId>spring-retry</artifactId>
<version>${revision}</version>
<name>Spring Retry</name>
```

https://repo1.maven.org/maven2/org/springframework/retry/spring-retry/2.0.9/spring-retry-2.0.9.pom

The actual version of the library would be expected, for instance: 2.0.9

**Comment by artembilan** [comment]
The `revision` is there as a property:
```
<properties>
<revision>2.0.9</revision>
```
Isn't it resolved properly?

**Comment by Kuba15** [comment]
> The `revision` is there as a property:
> 
> ```
> <properties>
> <revision>2.0.9</revision>
> ```
> 
> Isn't it resolved properly?

Ho sorry did not see your message.
There was indeed a resolution issue, you could also use the maven flatten plugin to replace the variable in the generated POM.

Thanks for the fix.
