### ISSUE TITLE
Class inheritance causes @Retryable annotations to stop working

### ISSUE THREAD

**Issue by GFriedrich** [spring-projects/spring-retry#475]
Hi,

I'm not sure if this is an expected behavior (and therefore this issue should be a feature request) or whether this is a bug, but this is what I've stumbled into:

When inheriting a class and placing the `@Retryable` annotation on top of the child class, the annotation is without any effect.
An example could look like this:
```java
abstract class AbstractClass {
    public int testMethod() {
        return 0;
    }
}

@Component
@Retryable
public class Test extends AbstractClass {}
```
I would expect that the `@Retryable` annotation gets applied to all public methods.

The workaround I came up with was redefining the methods on the child class like:
```java
@Component
@Retryable
public class Test extends AbstractClass {
    @Override
    public int testMethod() {
        return super.testMethod();
    }
}
```
In this case everything is working as expected - just that it causes me to implement methods for no obvious reason.

Thanks in advance for having a look at this.

**Comment by gaofengIt** [comment]
您好，我已经收到您的邮件，将尽快给您回复。

**Comment by artembilan** [comment]
I would say that this use-cases contradicts inheritance paradigm.
What you have with a `@Retryable` on a child class is fully similar if you would have a `private` method in that child class and would expect it to be visible in a super class.
The opposite is correct when `@Retryable` on a super class is applied to all its children.

Does that make sense to you?

@gaofengIt ,

please, stop spamming our issue tracker with automatic messages which does not reflect reality.
You never came back with any answers...

**Comment by GFriedrich** [comment]
> Does that make sense to you?

I would argue this is different and not comparable to your `private` example.
Because for my case here you could have a user using the `Test` class instance and this user doesn't know about where the method is defined. But it would always execute the method definition on the child class first. Which is the very same I would expect here: The definition should be initially picked from the child class and if unavailable use one of the superclasses.

The `private` example would be applicable if I try to call something within the superclass itself, which is not the case here, because I have somebody calling things from the outside.

**Comment by GFriedrich** [comment]
Ok, checked a bunch of other common Spring annotations and they all are implemented the same way.
So I guess this is a common design decision here and therefore I'm fine with it as it is, even though I don't really agree with it.
Thanks for you time @artembilan
~ CLOSED ~
