### ISSUE TITLE
`pom.xml` still contains references to `springsource.org` and `springsource.com` URLs

### ISSUE THREAD

**Issue by maloewe-ona** [spring-projects/spring-retry#479]
Hello,
the `pom.xml` still contains references to `springsource.org` and `springsource.com` URLs, however it seems these don't work anymore. Maybe it should refer to https://spring.io/ or just this repository here (https://github.com/spring-projects/spring-retry) instead?

https://github.com/spring-projects/spring-retry/blob/f92c90a2a519c57e4ab74bcc3b0521cc9593f500/pom.xml#L17-L20

(I cannot provide a pull request for this, sorry)

**Comment by fengkongling** [comment]
ok，亲~~~

**Comment by gaofengIt** [comment]
您好，我已经收到您的邮件，将尽快给您回复。
