### ISSUE TITLE
spring-boot-starter-retry should also bring in spring-boot-starter-aop

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-retry#52]
otherwise it plain doesn't work in a simple app

**Comment by wimdeblauwe** [comment]
Once that is done, it would be great if it was made available on start.spring.io as well.

**Comment by dsyer** [comment]
AFAIK there is no "spring-boot-starter-retry". The rationale for keeping spring-aop optional in this project has always been that it is, literally optional. I think maybe we could add spring-boot-start-aop with spring-retry in Initializr (in which case we should move this issue over there)?

**Comment by artembilan** [comment]
There is no `spring-boot-starter-retry` (at least) anymore.
And there is no good justification that `spring-retry` has to come automatically with `spring-boot-start-aop` even if it it only on Initializr.
From a real project perspective there is a limited number of use-cases where just single `spring-retry` would be need.
We usually develop a Microservice for some specific business task and that's where we pull from Initializr Spring Integration, Spring Batch, Spring Cloud Stream etc.
And that's from that Spring AOP is added as mandatory dependency anyway.

So, closing this as `Works as Designed`.
