### ISSUE TITLE
Not implemented EQUALS methods cause OOM while using AOP

### ISSUE THREAD

**Issue by alenavorozhbieva** [spring-projects/spring-retry#53]
AOP functionality creates classes dynamically if needed class has not exist yet. Equals method is called while checking if class has exist. In my case method equals in org.springframework.aop.framework.CglibAopProxy$ProxyCallbackFilter always returns false because of this code:
`if (!equalsPointcuts(thisAdvisor, thatAdvisor)) {
		return false;
}`
Because of there is no overriden EQUALS in org.springframework.retry.annotation.RetryConfiguration$AnnotationClassOrMethodPointcut.
Class loader stores all classes which it has loaded. So I get OOM because of many similar classes are stored in class loader (screen of heapdump is in https://jira.spring.io/browse/SPR-14738)

**Comment by garyrussell** [comment]
@alenavorozhbieva @dsyer FYI, I just added a [publish build plan](https://build.spring.io/browse/RETRY-PUB-1) for spring-retry and saw a couple of sporadic failures - class count off by one. Perhaps there's a race in there somewhere?

**Comment by dsyer** [comment]
Hmm. I thought I saw that briefly and it went away so I ignored it. The race must be in a lower layer, I think, possibly in the JDK even. Plug in a thread.sleep for now? Or only assert after the next iteration of the test?

**Comment by dsyer** [comment]
See 1b76dfa
