### ISSUE TITLE
Readme.md misleading about SimpleRetryPolicy

### ISSUE THREAD

**Issue by ukslim** [spring-projects/spring-retry#61]
Readme.md says:

      SimpleRetryPolicy policy = new SimpleRetryPolicy();
      policy.setRetryableExceptions(new Class[] {Exception.class});

... but SimpleRetryPolicy does not have a `setRetryableExceptions` method.

You can pass `Map<Class<? extends Throwable>, Boolean> retryableExceptions` as a constructor parameter -- Readme should say this instead.

**Comment by dsyer** [comment]
Thanks, fixed in bdda948

**Comment by ukslim** [comment]
Thanks - looks good, except that you did not delete the line containing `setRetryableExceptions` -- only the comment above it.

**Comment by dsyer** [comment]
Oops thanks again. Should be fixed now.
