### ISSUE TITLE
RetryContext needs to implement Serializable if it is stored in a distributed cache

### ISSUE THREAD

**Issue by ccpurvis** [spring-projects/spring-retry#62]
Hi. The Spring Batch MapRetryContextCache is not cluster aware and the Spring Batch Retry chapter suggests using a distributed cache.
See: http://docs.spring.io/spring-batch/reference/html/retry.html

I can do this only if the map value is serializable. This requires RetryContext and its fields (including implementations of RetryPolicy) to implement java.io.Serializable.

The ability for Spring Retry to be cluster aware is important and this would be a change much appreciated by many.
FYI: http://blog.ogorkis.net/2014/12/spring-amqp-statefulretryoperationsinte.html

Thanks!

**Comment by dsyer** [comment]
Actually only one of the existing `RetryContext` implementations is not explicitly serializable, and that looks like an error, but it's not easy to fix in 1.1.x. The problem is that, as you point out, all the `RetryPolicy` implementations will have to be serializable as well, in order to support composite patterns like `ExceptionClassifierRetryPolicy`. That seems like quite a big change.

Thanks for the blog reference (but it's not really relevant to this issue is it?). We could add more detail to the README to explain how to use the cache, I suppose.

**Comment by ccpurvis** [comment]
Hi Dave, thank you for your reply.

Ideally objects that are added to maps should be Serializable (actually,
probably using Externalizable interface in this case). I appreciate this is
a chunky change for you but will it be possible in the next release?

I added the blog post as it highlighted the importance of distributed maps
and, hence, of having Serializable objects that form part of the map. Not
only so that map is cluster-aware but also due to errors when reaching the
4096 hard limit (when performing Spring AMQP retries).

Let me know if possible. I would certainly appreciate the additional
details in the README - as I will attempt to create a distributed map using
Hazelcast custom serialisation of the RetryContext map contents (I do not
know how complicated this will be yet!).

Thanks so much for getting in touch and hope to hear from you soon,

Cam

**Comment by dsyer** [comment]
I'm really not sure anyone ever used a distributed cache with Spring Retry. How much value does it really have, given the overheads? Anyway, I don't think we want to stop you doing it, and the intention was always there that you could (but given this issue, clearly no-one ever has, and a lot of people use spring retry).

I added a couple of sentences to the README. Hope that helps, but if you want to add more please send a PR with a new section/paragraph.

I think we might be able to put this change in 1.2.0. I have a local branch that I'm evaluating, and it doesn't look like anything too disasterous for existing apps.

**Comment by ccpurvis** [comment]
Hello again Dave,

If you could put the change in to 1.2.0 I would be most grateful. Thank you
very much.

Once the RetryContext can be serialized, the overhead to us is minimal, as
we use Hazelcast already and I can simply implement a new context cache.

The reason we are looking at a distributed cache is that we use Spring-AMQP
which, in turn, uses Spring-Retry. We require our RabbitMQ message failures
to be retried, based on the configured number of retries, regardless of
number of nodes in our cluster. At the moment it will retry [configured
number multiplied by number of nodes]. For example, we set a failed message
to be retried 3 times, but for a 100 node cluster that will result in 300
retry attempts!

Additionally, we have seen the behaviour noted by Stanislaw:
It turned out you actually *MUST IMPLEMENT* a distributed
RetryContextCache. It does not have to be clustered, but still default Map
based cache will sooner or later blow up in production. The problem with
default implementation is that it can store 4096 keys and there is no
expiry. If you have transient issues it might happen that it will fail on
server A, and then server B will correctly consume message. Then you end up
with 4095 limit... When you reach 0, Spring Retry starts throwing
*RetryCacheCapacityExceededException* and no messages ever end up in DLQ.

Many thanks,
Campbell

**Comment by ccpurvis** [comment]
Hello Dave,

FYI I certainly see the following objects that form part of the map
requiring serialization:

java.io.NotSerializableException:
com.earthport.rabbit.support.retry.StatefulExponentialBackoff$ExponentialBackOffContext

java.io.NotSerializableException:
org.springframework.classify.SubclassClassifier


Best wishes, Cam

**Comment by dsyer** [comment]
Thanks, that's useful. Can you try a snapshot and let me know if it works for you?

**Comment by ccpurvis** [comment]
Hi Dave. Yes, of course. Just let me know when available. Thank you very
much.

Cam

**Comment by dsyer** [comment]
Already available as a snapshot (but not in github yet).

**Comment by ccpurvis** [comment]
Hi. I have tested two scenarios that were originally failing on map.put with a java.io.NotSerializableException:

1. Success
I can now put a org.springframework.retry.policy.SimpleRetryPolicy$SimpleRetryContext in the map. Originally, the BackOffContext failed to serialize.

2. Failure
I still cannot put a org.springframework.retry.policy.ExceptionClassifierRetryPolicy$ExceptionClassifierRetryContext in the map due to the inability to serialize SubclassClassifier.
java.io.NotSerializableException: org.springframework.classify.SubclassClassifier

**Comment by dsyer** [comment]
OK, try again please. I'm slightly more nervous about that change, but let's see if it works at least.

**Comment by ccpurvis** [comment]
Hi Dave, sorry for the delay, I have created some tests for this usage.

Although the map values are now being serialized, it appears the serialization is not maintaining object state. Specifically, I see the RetryContextSupport count attribute is always initialized back to zero. 
This is where the map value is: org.springframework.retry.policy.SimpleRetryPolicy$SimpleRetryContext

I will also test report back on the scenario for a map value: org.springframework.retry.policy.ExceptionClassifierRetryPolicy$ExceptionClassifierRetryContext

**Comment by dsyer** [comment]
That's odd. `SimpleRetryPolicy` always works fine for me, and I can see the count coming back from deserialization. Can you provide a simple test, e.g. using `SerializationUtils`?

**Comment by ccpurvis** [comment]
Hi. I am wondering if it would it be possible to implement Serializable on RetryContext? This is the value that  MapRetryContextCache puts in to the map.

**Comment by dsyer** [comment]
`RetryContext` is already implicitly `Serializable` (since 1.0.0) since it extends `AttributeAccessor`. The problems here were all to do with stuff in the context that wasn't serializable. Can you make a test?

**Comment by ccpurvis** [comment]
Hi there, to confirm?
org.springframework.retry.RetryContext 
extends
org.springframework.core.AttributeAccessor

But AttributeAccessor does not implement or extend Serializable.
..only AttributeAccessorSupport?

I am using 
<artifactId>spring-retry</artifactId>
<version>1.2.0.BUILD-20161124.134613-9</version>
and 
<artifactId>spring-core</artifactId>
<spring.version>4.3.4.RELEASE</spring.version>

**Comment by ccpurvis** [comment]
I do see the implementation classes extend RetryContextSupport which extends AttributeAccessorSupport.

**Comment by ccpurvis** [comment]
Hi again Dave,

I have written a unit test that confirms the RetryContext can be successfully serialized and deserialized from a map. Thank you.

However, I have written a test from the RetryTemplate level that also includes the context cache behaviour. The retry count is not being incremented after each register. I believe the retry logic may be performing an in-place update of the retry context in the map? This would not work for serialized map values.

**Comment by dsyer** [comment]
Can you share the test then?

**Comment by ccpurvis** [comment]
Yes of course. I have attached the test and an implementation of RetryContextCache that serializes the map values. I have also added some logging which shows that when using the org.springframework.retry.policy.MapRetryContextCache there may be in-place update to the map value.

[retry-test.zip](https://github.com/spring-projects/spring-retry/files/618683/retry-test.zip)

**Comment by dsyer** [comment]
I can see the issue in your test but it's nothing to do with serializability is it? It's just that the cache is populated before the context is updated. Do you want to open a separate issue for that? I think we can close this one?

**Comment by ccpurvis** [comment]
Hiya, the failure only occurs when serializing the map values. I am happy to close this and have created a new issue:
https://github.com/spring-projects/spring-retry/issues/65
Thanks so much for you help so far Dave.

**Comment by dsyer** [comment]
Fixed in 2b4c4ee37
