### ISSUE TITLE
Comparing with com.github.rholder:guava-retrying - missing TimeLimiter

### ISSUE THREAD

**Issue by stepio** [spring-projects/spring-retry#69]
Hi @garyrussell ,

Thanks again for supporting this project, hope you're fine. I have a question/suggestion.

As of now I'd like to use Spring (instead of other alternatives) in all the supported cases - just to prevent mess with different dependencies, conflicts and so on. `Spring Retry` is great component, but before I've started using it, I've used another good project - Guava Retrying:
https://github.com/rholder/guava-retrying

In most cases it's very similar to Spring Retry and I'd like to focus on using the latter one. But there is a small use case which I miss, let me explain it to you.

I mostly use retry functionality for handling I/O errors. Including the database querying. And we have some sophisticated network issue when database connections are dropped externally while executing a complex (long-running) SQL query and no timeout can drop this connection afterwards - the thread just hangs infinitely. After long and painful troubleshooting I've invented a solution which works for us:

1. Retry database querying in case of exceptions (up to 3 times).
2. Configure execution timeout for database querying (up to 5 minutes).
So no, if connection is silently dropped, the timeout exception is thrown and retried.

Using the above mentioned Guava Retrying project I'm able to configure both timeout and retry in one place:
```java
    @Bean
    public Retryer<ResponseEntity<String>> guavaRetryer() {
        return RetryerBuilder.<ResponseEntity<String>>newBuilder()
                .retryIfException()
                .withWaitStrategy(WaitStrategies.exponentialWait(config.getRetryWaitMultiplier(), config.getRetryWaitMaxTime(), TimeUnit.MILLISECONDS))
                .withStopStrategy(StopStrategies.stopAfterAttempt(config.getRetryMaxCount()))
                .withAttemptTimeLimiter(AttemptTimeLimiters.fixedTimeLimit(config.getRetryTimeout(), TimeUnit.MILLISECONDS))
                .withRetryListener(new RetryListener() {
                    public <V> void onRetry(Attempt<V> attempt) {
                        if (attempt.hasException()) {
                            logger.warn("Attempt #{}, exception occurred: {}", attempt.getAttemptNumber(), attempt.getExceptionCause().getMessage());
                        }
                    }
                })
                .build();
    }
```
This line does the timeout:
```java
                .withAttemptTimeLimiter(AttemptTimeLimiters.fixedTimeLimit(config.getRetryTimeout(), TimeUnit.MILLISECONDS))
```

But unfortunately such a functionality is missing in Spring Retry (or I have not found it). What do you think about supporting this? Or would you recommend any other alternative?

P.S.: I've tried configuring transaction timeouts with Spring Transactions, but this did not help - for example, in some cases the "hanging" occurred even before the transaction itself was initiated. Also it's just feels better to have such an external limiter (such a "backup plan") anyway.

**Comment by garyrussell** [comment]
@stepio Generally, such operations (socket read) are not interruptible so I don't know how they can kill the thread that's waiting for a query to complete.

It would be interesting to see how that is implemented; typically, blocking IO operations (on sockets) are best handled by setting a timeout on the socket. Or, if you have access to the raw socket, closing it from some other thread so the waiting thread gets an `IOException`. Typically, the underlying driver's socket is not available for such low-level activities, though.

Spring retry is completely passive (intercepting the call) and doesn't have any active components (timers etc). Even if it did, I am not sure how useful it would be in this case, since the operation is, generally, uninterruptible.

**Comment by stepio** [comment]
In our case, most probably that's a problem in `c3p0` library - it's not able to handle my "corner" case correctly. We were able to reproduce the issue by blocking the connection's port at DB side - in this case the appropriate connection just hangs and stays so until it's interrupted externally. Before we introduced `Guava Retrying`, the only solution was to restart the application. Now application behaves correctly and everyone is happy.

I do understand that correct fix would be to find out the network root cause, or fix c3p0. But that's a real world - I was not able to do so, but limiting did the job. Also I've tried using Apache DBCP, but it worked even worse in this situation.

Talking about how limiting is implemented, `Guava Retrying` project uses `Guava` code with `Future`:
https://github.com/google/guava/blob/master/guava/src/com/google/common/util/concurrent/SimpleTimeLimiter.java
```java
  public <T> T callWithTimeout(
      Callable<T> callable, long timeoutDuration, TimeUnit timeoutUnit, boolean amInterruptible)
      throws Exception {
    checkNotNull(callable);
    checkNotNull(timeoutUnit);
    checkArgument(timeoutDuration > 0, "timeout must be positive: %s", timeoutDuration);
    Future<T> future = executor.submit(callable);
    try {
      if (amInterruptible) {
        try {
          return future.get(timeoutDuration, timeoutUnit);
        } catch (InterruptedException e) {
          future.cancel(true);
          throw e;
        }
      } else {
        return Uninterruptibles.getUninterruptibly(future, timeoutDuration, timeoutUnit);
      }
    } catch (ExecutionException e) {
      throw throwCause(e, true);
    } catch (TimeoutException e) {
      future.cancel(true);
      throw new UncheckedTimeoutException(e);
    }
  }
```

**Comment by stepio** [comment]
So, long story short, I think that supporting such a case here makes sence. If you think that it's not necessary - Ok, I'll close the issue.

**Comment by garyrussell** [comment]
I am not dismissing the issue; I just don't have time to dig into guava to see how they can possibly deal with an uninterruptible hung thread; perhaps they always hand off to another thread and just leave it hanging after the timeout - which would be a memory leak and not so good a solution.

**Comment by garyrussell** [comment]
Handing off to another thread like that will break transactions.

**Comment by garyrussell** [comment]
Handing off to another thread like that will break transactions in Spring, so it wouldn't have universal applicability. I can see it might be useful in other scenarios though.

However, if the thread is truly hung uninterruptibly; it would cause a memory leak; which is not really a good solution.
