### ISSUE TITLE
Spring Boot auto configuration

### ISSUE THREAD

**Issue by mkopylec** [spring-projects/spring-retry#70]
Hi is there any plan to add auto configuration to [spring-boot-autoconfigure](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-autoconfigure)?
I can help if you like.

**Comment by dsyer** [comment]
That would be a question for the spring boot team (in the spring boot guithub tracker, please). I'm not sure there would be very much to do - if you `@EnableRetry` it's already pretty opinionated. What would you expect the autoconfig to do?

**Comment by mkopylec** [comment]
I have rethink it and I supose you are right, I forgot about `@EnableRetry`.
Closing the issue.
