### ISSUE TITLE
Release version of spring-retry

### ISSUE THREAD

**Issue by meenarc** [spring-projects/spring-retry#91]
Is there a  maven release version of this available?
Also what are the plans in terms of including this in spring-cloud or spring-boot?
Am trying to look at whether I can use this in place of the netflix circuit breaker that is available as part of Spring Cloud.
Thanks
Meena

**Comment by fatroom** [comment]
Hi Meena,
the spring retry is available via the maven central:

    <dependency>    
      <groupId>org.springframework.retry</groupId>    
      <artifactId>spring-retry</artifactId>    
      <version>1.2.1.RELEASE</version>
    </dependency>

I'm not a part of the development team, so can not answer any questions regarding plans.

**Comment by dsyer** [comment]
Version 1.2.1 is managed by Spring Boot 1.5.x (since 1.5.8 I think at least). You can use `@CircuitBreaker` to replace `@HystrixCommand`, but there is no support for metrics yet (the data are there but no-one is collecting them). You should ask about that over in spring-cloud-netflix probably.
